<template>
  <div class="footer-quote">{{ quote }}</div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'

const quote = ref('Loading quote...')

// const QUOTES: string[] = [
//   "Simplicity is the soul of efficiency. — Austin Freeman",
//   "Well begun is half done. — Aristotle",
//   "Focus on being productive instead of busy. — Tim Ferriss",
//   "Perseverance is not a long race; it is many short races one after another. — Walter Elliot",
//   "Action is the foundational key to all success. — Picasso"
// ]
//
// const QUOTES: string[] = [
//   "Simplicity is the soul of efficiency. — Austin Freeman",
//   "Well begun is half done. — Aristotle",
//   "Focus on being productive instead of busy. — Tim Ferriss",
//   "Perseverance is not a long race; it is many short races one after another. — Walter Elliot",
//   "Action is the foundational key to all success. — Picasso",
//   "Stay hungry. Stay foolish. — Steve Jobs",
//   "Whether you think you can, or you think you can't—you're right. — Henry Ford",
//   "Genius is one percent inspiration and ninety-nine percent perspiration. — Thomas Edison",
//   "The journey of a thousand miles begins with a single step. — Lao Tzu",
//   "You miss 100% of the shots you don’t take. — Wayne Gretzky",
//   "No pressure, no diamonds. — Thomas Carlyle",
//   "He who has a why can bear any how. — Nietzsche",
//   "Do what you can, with what you have, where you are. — Theodore Roosevelt",
//   "Fortune favors the bold. — Latin Proverb",
//   "Innovation distinguishes between a leader and a follower. — Steve Jobs",
//   "Quality means doing it right when no one is looking. — Henry Ford",
//   "It always seems impossible until it’s done. — Nelson Mandela",
//   "Fall seven times, stand up eight. — Japanese Proverb",
//   "Discipline equals freedom.",
//   "Consistency beats intensity.",
//   "Small daily wins compound.",
//   "Progress is a direction, not a speed.",
//   "Start small. Start now.",
//   "Be relentless, be kind.",
//   "Hard choices, easy life. Easy choices, hard life.",
//   "Courage is a decision before it’s a feeling.",
//   "Do the next right thing.",
//   "Sharp tools, steady hands, patient heart.",
//   "Ship early, ship often.",
//   "Measure in decades, act in days.",
//   "Build what you wish existed.",
//   "Done is better than perfect.",
//   "Perfection is a moving target.",
//   "Repeat what works, refine what doesn’t.",
//   "Trust is built in tiny moments.",
//   "Honesty costs less than permission.",
//   "Integrity is doing the hard obvious.",
//   "Character is built off-camera.",
//   "Tell the truth, even quietly.",
//   "Promises are debts with interest.",
//   "Say less, mean more.",
//   "Clarity is kindness.",
//   "Boundaries are bridges for respect.",
//   "Kindness scales.",
//   "Confidence is earned in private.",
//   "Your future is a daily vote.",
//   "Habits write your autobiography.",
//   "Motivation starts you; systems keep you.",
//   "Talent starts the story; grit finishes it.",
//   "Boredom is the tax on mastery.",
//   "Practice until it looks like talent.",
//   "Repetition is rehearsal for excellence.",
//   "Be stubborn on vision, flexible on details.",
//   "Curiosity outlives certainty.",
//   "Prototype your opinions.",
//   "Constraints are invitations.",
//   "Simplicity survives contact with reality.",
//   "Elegant is when nothing can be removed.",
//   "If it isn’t written, it isn’t real.",
//   "Slow is smooth; smooth is fast.",
//   "Momentum loves modest beginnings.",
//   "The obstacle is the way. — Marcus Aurelius",
//   "Attention is your most generous currency.",
//   "Focus is saying no nicely.",
//   "What you ignore, you endorse.",
//   "What you measure, you improve.",
//   "Inputs you control; outputs you influence.",
//   "Decide once; execute often.",
//   "Plan in pencil; commit in ink.",
//   "Strategy is choosing what not to do. — Porter",
//   "Direction beats speed when you’re wrong.",
//   "Feedback is a shortcut you pay for with ego.",
//   "Silence is data.",
//   "Listen to learn, not to load.",
//   "Strong opinions, light grip.",
//   "Disagree without disrespect.",
//   "Your heroes are human; so are you.",
//   "Confidence grows where evidence lives.",
//   "Self-esteem is self-trust in action.",
//   "Compare less, create more.",
//   "Be the person your child thinks you are.",
//   "Love is spelled T-I-M-E.",
//   "Presence is the best present.",
//   "Read the story before correcting the grammar.",
//   "Little eyes learn from little moments.",
//   "Hold the phone after you hold the hand.",
//   "Your tone becomes their inner voice.",
//   "Routines are hugs on the calendar.",
//   "Kids need roots and wings.",
//   "Patience is parental superpower.",
//   "You can’t pour from an empty cup.",
//   "Rest is a responsibility, not a reward.",
//   "Whitespace is where wisdom whispers.",
//   "Saying yes to everything says no to excellence.",
//   "Your calendar is your character.",
//   "Schedule your priorities, don’t prioritize your schedule.",
//   "If it matters weekly, block it daily.",
//   "Five minutes is a start, not a stall.",
//   "Don’t break the chain.",
//   "One more rep. One more line. One more page.",
//   "Win the morning; don’t lose the night.",
//   "Seek progress, not permission.",
//   "Ask better questions.",
//   "Curiosity beats credentials.",
//   "Build to learn; learn to build.",
//   "Make it simple; then make it obvious.",
//   "Delight is in the details.",
//   "Every bug teaches something.",
//   "Read the error; it’s trying to help.",
//   "Logs are love letters from your code.",
//   "Premature optimization steals joy.",
//   "If it’s manual twice, automate once.",
//   "Write code for the reader.",
//   "Documentation is part of the product.",
//   "Tests protect tomorrow.",
//   "Naming is design by another word.",
//   "Refactor like a gardener, not a bulldozer.",
//   "Deadlines focus; values guide.",
//   "Say the hard thing early.",
//   "Be brave enough to be bad at first.",
//   "First drafts are permission, not prophecy.",
//   "Creativity is messy on purpose.",
//   "Inspiration visits workers.",
//   "Ideas are free; execution is rent.",
//   "Vision without iteration is hallucination.",
//   "Direction over drama.",
//   "Less friction, more flow.",
//   "Energy is a strategy.",
//   "Move your body; move your mind.",
//   "Breathe deeper than your worries.",
//   "Confidence is a byproduct of keeping promises to yourself.",
//   "Protect your attention from cheap alerts.",
//   "Information isn’t transformation.",
//   "Knowledge compounds; wisdom edits.",
//   "Experience is feedback with a longer leash.",
//   "Saying no creates space for better yeses.",
//   "Most emergencies aren’t.",
//   "Urgent is loud; important is quiet.",
//   "Don’t outsource your self-respect.",
//   "You teach people how to treat you.",
//   "Kind doesn’t mean agreeable.",
//   "Respect speaks last and listens first.",
//   "Gratitude amplifies enough.",
//   "Joy is excellent fuel.",
//   "Hope is a discipline.",
//   "Optimism is practical risk management.",
//   "Expect headwinds; train legs.",
//   "Storms reveal anchors.",
//   "Scars are proof you kept going.",
//   "Failure is data, not identity.",
//   "Fall forward, learn fast.",
//   "Regret is heavier than effort.",
//   "Hard today, easy tomorrow.",
//   "Today’s discomfort is tomorrow’s competence.",
//   "Pain is tuition for growth.",
//   "Sweat is the sound of progress.",
//   "Direction changes are not defeats.",
//   "Reset is a strategy.",
//   "Prepare so luck can find you.",
//   "Be so good they can’t ignore you. — Steve Martin",
//   "Luck favors prepared minds. — Louis Pasteur",
//   "We become what we behold. — William Blake",
//   "Excellence is a habit of choices.",
//   "Habits are how beliefs become biology.",
//   "Make the right thing the easy thing.",
//   "Environment eats willpower for breakfast.",
//   "Remove the friction you can.",
//   "Automate kindness to your future self.",
//   "Future you is watching.",
//   "Write the note you wish you had yesterday.",
//   "Stack tiny advantages.",
//   "Aim for better, not best.",
//   "Perfect is brittle; progress is flexible.",
//   "Simple scales; complex fails.",
//   "Clarity creates speed.",
//   "If you can’t explain it simply, you don’t understand it. — Einstein",
//   "A confused mind says no.",
//   "Alignment before assignment.",
//   "Think long, decide once, execute daily.",
//   "Pace yourself; you’re building a life.",
//   "Work hard, unplug harder.",
//   "Rest isn’t quitting; it’s refueling.",
//   "Sprints need seasons.",
//   "Balance is a verb.",
//   "Boundaries protect what you value.",
//   "Protect the morning; defend the evening.",
//   "Worry pretends to be preparation.",
//   "Preparation is kindness to your future self.",
//   "Rehearse success in small ways.",
//   "Start where your feet are.",
//   "Where focus goes, momentum grows.",
//   "You can do hard things.",
//   "Don’t wait to feel ready.",
//   "Act your way into confidence.",
//   "Competence cures anxiety.",
//   "Reps reduce fear.",
//   "Climb the staircase you can see.",
//   "What you repeat, you remember.",
//   "Practice doesn’t make perfect; practice makes permanent.",
//   "Choose your hard.",
//   "When in doubt, tidy.",
//   "Order reduces friction.",
//   "Systems save willpower.",
//   "Standardize to simplify.",
//   "Be allergic to ambiguity you can fix.",
//   "Assumptions are expensive; ask.",
//   "Document the decision when the why is fresh.",
//   "Communicate twice as clearly as you think you should.",
//   "If it matters, write it down.",
//   "Meetings need purpose or pruning.",
//   "Short meetings reward preparation.",
//   "Asynchronous is kind to deep work.",
//   "Deep work dislikes open tabs.",
//   "Move slow to move well.",
//   "Hurry hides mistakes.",
//   "Calm is a competitive advantage.",
//   "Grace under pressure is practiced, not gifted.",
//   "Your pace is part of your product.",
//   "Speed matters after clarity.",
//   "Direction, then velocity.",
//   "Think in systems; act in steps.",
//   "Zoom out to aim; zoom in to execute.",
//   "Notes are external RAM.",
//   "Second brains need first habits.",
//   "Reduce decisions with default choices.",
//   "Default to generosity.",
//   "Assume positive intent; verify actual impact.",
//   "Kind truth beats comfortable silence.",
//   "Honesty without empathy is cruelty.",
//   "Empathy without honesty is avoidance.",
//   "Lead with questions, not answers.",
//   "Leaders go first and eat last.",
//   "Culture is what you allow.",
//   "Standards rise when examples lead.",
//   "Your example is louder than your advice.",
//   "Teach by doing and narrating.",
//   "Praise effort; coach process; celebrate learning.",
//   "Catch people doing it right.",
//   "Feedback lands on trust first.",
//   "Trust arrives on foot and leaves on horseback.",
//   "Promises kept are quiet miracles.",
//   "Don’t break trust to win time.",
//   "Reputation is compound interest on behavior.",
//   "Be reliable in small things.",
//   "Arrive prepared; leave grateful.",
//   "Say thank you specifically.",
//   "Credit is abundant; share it.",
//   "Ownership isn’t blame; it’s agency.",
//   "If it’s everyone’s job, it’s no one’s job.",
//   "Clear owners, clear outcomes.",
//   "Goals need rhythms.",
//   "Milestones celebrate momentum.",
//   "Celebrate progress without declaring victory.",
//   "Humility upgrades learning speed.",
//   "Curiosity disarms defensiveness.",
//   "Assume the role of student longer.",
//   "Your heroes practiced longer than you think.",
//   "Talent is a multiplier of practice.",
//   "Grit is a multiplier of time.",
//   "Joy is a multiplier of grit.",
//   "Choose useful suffering.",
//   "Pain with purpose is perseverance.",
//   "Relentless is patient, not frantic.",
//   "Relentless shows up on boring days.",
//   "Relentless rests, then returns.",
//   "Relentless is nice to the clerk.",
//   "Relentless does reps when watched and when not.",
//   "Relentless forgives itself and continues.",
//   "Relentless keeps promises to future self.",
//   "Relentless chooses growth over comfort.",
//   "Relentless treats obstacles as practice.",
//   "Relentless is grateful and grounded.",
//   "Relentless knows when to stop for safety.",
//   "Relentless says ‘again’.",
//   "Love is a renewable resource.",
//   "Love listens before it solves.",
//   "Love is spelled attention.",
//   "Love is low-ego service.",
//   "Love protects the room, not the point.",
//   "Love chooses presence over performance.",
//   "Love holds space for imperfect people.",
//   "Love makes room for repair.",
//   "Apologies are bridges you build yourself.",
//   "Forgiveness frees the forgiver.",
//   "Grace is strength with manners.",
//   "Be tough on standards, soft on people.",
//   "People over processes; processes to protect people.",
//   "Innovation needs psychological safety.",
//   "Creativity needs constraint and care.",
//   "New ideas need a nursery.",
//   "Prototype the risky parts first.",
//   "Kill your darlings kindly.",
//   "If it’s not a hell yes, it’s a polite no.",
//   "Dream in color; schedule in grayscale.",
//   "Ambition without gratitude is hunger without taste.",
//   "Ambition with empathy scales better.",
//   "Serve first; sell second.",
//   "Value travels faster than pitch.",
//   "Solve a real pain, beautifully.",
//   "The market respects outcomes, not effort.",
//   "Be brave enough to niche.",
//   "A small yes beats a huge maybe.",
//   "Make the first version useful.",
//   "Version one teaches version two.",
//   "Every feature costs forever.",
//   "Less to maintain, more to love.",
//   "Delight is a feature.",
//   "Make it obvious, then delightful.",
//   "Documentation is a love letter to users.",
//   "Support is product, not punishment.",
//   "Your brand is a promise kept repeatedly.",
//   "Reputation arrives before you speak.",
//   "Trust is the ultimate growth hack.",
//   "Honesty is efficient.",
//   "Say what you mean, kindly.",
//   "Mean what you say, consistently.",
//   "Keep what you promise, publicly and privately.",
//   "Admit mistakes faster than they spread.",
//   "Own the miss, outline the fix.",
//   "Apologize without excuses.",
//   "Be the teammate you want to have.",
//   "Lift as you climb.",
//   "Teach someone your shortcuts.",
//   "Mentors are accelerators.",
//   "Ask for help like a pro.",
//   "Gratitude turns work into worship.",
//   "Serve the work, not your image.",
//   "Let the work speak; make it eloquent.",
//   "Craft is care made visible.",
//   "Mastery hides in maintenance.",
//   "Excellence is ordinary things, extraordinarily well.",
//   "Simplicity today preserves agility tomorrow.",
//   "Today’s habits are tomorrow’s culture.",
//   "Compete with your past, not your peers.",
//   "Be a little better, a lot of times.",
//   "Your edge is where you’re consistent.",
//   "Do fewer things, better.",
//   "Focus turns average into exceptional.",
//   "Talent may open doors; character keeps rooms.",
//   "The right room changes the work.",
//   "Find rooms where effort echoes.",
//   "If you’re the smartest, find a new room.",
//   "Ask ‘what did I learn today?’",
//   "Leave places better than you found them.",
//   "Take notes your future self can understand.",
//   "Make your calendar match your goals.",
//   "Protect deep work like a meeting with yourself.",
//   "Great days start the night before.",
//   "Sleep is a superpower disguised as surrender.",
//   "Move daily; think clearly.",
//   "Nutrition is productivity’s quiet partner.",
//   "Water and walks fix more than we admit.",
//   "Sunlight is software for mood.",
//   "Nature is a factory reset.",
//   "Gratitude writes brighter stories.",
//   "Kindness multiplies in private.",
//   "Hope is contagious; be a carrier.",
//   "Be useful, and be you.",
//   "Authenticity removes the tax of pretending.",
//   "Original beats impressive.",
//   "Own your weird; it’s your signature.",
//   "Vulnerability invites real connection.",
//   "The right ‘no’ protects the best ‘yes’.",
//   "If everything is important, nothing is.",
//   "Priorities require tradeoffs; choose consciously.",
//   "Let your calendar show your courage.",
//   "Courage is the first input.",
//   "Fear is a compass; don’t camp there.",
//   "Walk through the door courage opens.",
//   "The next step is usually small.",
//   "When stuck, subtract.",
//   "When tired, rest; when ready, return.",
//   "When overwhelmed, one thing.",
//   "When unsure, ask; when sure, check.",
//   "When angry, wait; when calm, write.",
//   "When afraid, breathe; when brave, begin.",
//   "One day or day one—decide.",
//   "The best time was then; the second best is now.",
//   "Aim for progress, prepare for persistence.",
//   "Leave room for miracles and mistakes.",
//   "Gratitude in advance is faith.",
//   "Be a thermostat, not a thermometer.",
//   "Lead with calm, not calories of chaos.",
//   "Stay curious longer than comfortable.",
//   "Do the work; trust the compounding.",
//   "Keep going: your future is watching.",
//   "Make something today your future self will thank you for."
// ];

function dayOfYear(d = new Date()) {
  const start = new Date(d.getFullYear(), 0, 0);
  const diff = d.getTime() - start.getTime()
  const oneDay = 24 * 60 * 60 * 1000
  return Math.floor(diff / oneDay) // 1..366
}

onMounted(() => {
  const idx = dayOfYear() % QUOTES.length
  quote.value = QUOTES[idx]
})
</script>

<style scoped>
.footer-quote {
  flex: 1; text-align: center; font-style: italic; font-size: 1rem; padding: 0 20px; opacity: .9;
}
</style>
