export type Quote = { text: string; author: string };

export const QUOTES: Quote[] = [
  { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
  { text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Whether you think you can, or you think you can’t—you’re right.", author: "Henry Ford" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas A. Edison" },
  { text: "I have not failed. I’ve just found 10,000 ways that won’t work.", author: "Thomas A. Edison" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "The best way out is always through.", author: "Robert Frost" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { text: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { text: "Hard choices, easy life. Easy choices, hard life.", author: "Jerzy Gregorek" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act but a habit.", author: "Will Durant" },
  { text: "The impediment to action advances action; what stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "He who has a why can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn" },
  { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Perseverance is not a long race; it is many short races one after another.", author: "Walter Elliot" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Amateurs sit and wait for inspiration; the rest of us just get up and go to work.", author: "Stephen King" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Any sufficiently advanced technology is indistinguishable from magic.", author: "Arthur C. Clarke" },
  { text: "Make it work, make it right, make it fast.", author: "Kent Beck" },
  { text: "Premature optimization is the root of all evil.", author: "Donald Knuth" },
  { text: "If I have seen further it is by standing on the shoulders of giants.", author: "Isaac Newton" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "What you do speaks so loudly that I cannot hear what you say.", author: "Ralph Waldo Emerson" },
  { text: "Do not go where the path may lead; go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "Knowledge will give you power, but character respect.", author: "Bruce Lee" },
  { text: "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn" },
  { text: "Love recognizes no barriers.", author: "Maya Angelou" },
  { text: "If you judge people, you have no time to love them.", author: "Mother Teresa" },
  { text: "It’s not how much we give, but how much love we put into giving.", author: "Mother Teresa" },
  { text: "Children learn more from what you are than what you teach.", author: "W.E.B. Du Bois" },
  { text: "The way we talk to our children becomes their inner voice.", author: "Peggy O’Mara" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "If opportunity doesn’t knock, build a door.", author: "Milton Berle" },
  { text: "Don’t let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { text: "It’s not what you look at that matters, it’s what you see.", author: "Henry David Thoreau" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "If you really want to do something, you’ll find a way. If not, you’ll find an excuse.", author: "Jim Rohn" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "What would you do if you weren’t afraid?", author: "Sheryl Sandberg" },
  { text: "Move fast and break things.", author: "Mark Zuckerberg" },
  { text: "If you are not embarrassed by the first version of your product, you’ve launched too late.", author: "Reid Hoffman" },
  { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
  { text: "Coming together is a beginning; keeping together is progress; working together is success.", author: "Henry Ford" },
  { text: "Honesty is the first chapter in the book of wisdom.", author: "Thomas Jefferson" },
  { text: "No legacy is so rich as honesty.", author: "William Shakespeare" },
  { text: "Integrity is doing the right thing, even when no one is watching.", author: "C. S. Lewis" },
  { text: "The time is always right to do what is right.", author: "Martin Luther King Jr." },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Gratitude turns what we have into enough.", author: "Aesop" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Jean-Jacques Rousseau" },
  { text: "We do not remember days, we remember moments.", author: "Cesare Pavese" },
  { text: "To be in your children’s memories tomorrow, you have to be in their lives today.", author: "Barbara Johnson" },
  { text: "Children are not things to be molded, but people to be unfolded.", author: "Jess Lair" },
  { text: "The greatest gifts you can give your children are the roots of responsibility and the wings of independence.", author: "Denis Waitley" },
  { text: "Train people well enough so they can leave; treat them well enough so they don’t want to.", author: "Richard Branson" },
  { text: "It’s fine to celebrate success, but it is more important to heed the lessons of failure.", author: "Bill Gates" },
  { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
  { text: "Consistency beats intensity.", author: "Original" },
  { text: "Small daily wins compound.", author: "Original" },
  { text: "Reps reduce fear.", author: "Original" },
  { text: "Start small. Start now.", author: "Original" },
  { text: "Progress is a direction, not a speed.", author: "Original" },
  { text: "One more step is a strategy.", author: "Original" },
  { text: "Momentum loves modest beginnings.", author: "Original" },
  { text: "Fall forward; learn fast.", author: "Original" },
  { text: "Hard today, easy tomorrow.", author: "Original" },
  { text: "Today’s discomfort is tomorrow’s competence.", author: "Original" },
  { text: "Pain is tuition for growth.", author: "Original" },
  { text: "Reset is a strategy.", author: "Original" },
  { text: "Storms reveal anchors.", author: "Original" },
  { text: "Scars are proof you kept going.", author: "Original" },
  { text: "Keep going: your future is watching.", author: "Original" },
  { text: "Tiny progress beats loud intentions.", author: "Original" },
  { text: "Grit shows up on boring days.", author: "Original" },
  { text: "Perseverance is patient, not frantic.", author: "Original" },
  { text: "Finish the sentence, then the story.", author: "Original" },
  { text: "Long games reward short reps.", author: "Original" },
  { text: "Honesty costs less than permission.", author: "Original" },
  { text: "Say what you mean, kindly.", author: "Original" },
  { text: "Integrity is doing the hard obvious.", author: "Original" },
  { text: "Trust arrives on foot and leaves on horseback.", author: "Original" },
  { text: "Promises kept are quiet miracles.", author: "Original" },
  { text: "Kind truth beats comfortable silence.", author: "Original" },
  { text: "Respect speaks last and listens first.", author: "Original" },
  { text: "Clarity is kindness.", author: "Original" },
  { text: "Your calendar is your character.", author: "Original" },
  { text: "Reputation is compound interest on behavior.", author: "Original" },
  { text: "Admit mistakes faster than they spread.", author: "Original" },
  { text: "Own the miss, outline the fix.", author: "Original" },
  { text: "Apologize without excuses.", author: "Original" },
  { text: "Say less, mean more.", author: "Original" },
  { text: "Accountability is love for the future.", author: "Original" },
  { text: "Boundaries teach respect.", author: "Original" },
  { text: "Consistency is credible.", author: "Original" },
  { text: "Honesty is efficient.", author: "Original" },
  { text: "Keep promises to yourself first.", author: "Original" },
  { text: "Character is built off-camera.", author: "Original" },
  { text: "Confidence is earned in private.", author: "Original" },
  { text: "Self-esteem is self-trust in action.", author: "Original" },
  { text: "Compare less, create more.", author: "Original" },
  { text: "Act your way into confidence.", author: "Original" },
  { text: "Competence cures anxiety.", author: "Original" },
  { text: "You are the author of your attention.", author: "Original" },
  { text: "Be the person your child thinks you are.", author: "Original" },
  { text: "Your future is a daily vote.", author: "Original" },
  { text: "Habits write your autobiography.", author: "Original" },
  { text: "Original beats impressive.", author: "Original" },
  { text: "Own your weird; it’s your signature.", author: "Original" },
  { text: "Authenticity removes the tax of pretending.", author: "Original" },
  { text: "Be useful, and be you.", author: "Original" },
  { text: "The more you know yourself, the freer you become.", author: "Original" },
  { text: "Confidence grows where evidence lives.", author: "Original" },
  { text: "Keep the promises you make to yourself.", author: "Original" },
  { text: "Talk to yourself like someone you love.", author: "Original" },
  { text: "Let action quiet the inner critic.", author: "Original" },
  { text: "Do the work; let the work talk.", author: "Original" },
  { text: "Write a story you’re proud to reread.", author: "Original" },
  { text: "Love is spelled T-I-M-E.", author: "Original" },
  { text: "Presence is the best present.", author: "Original" },
  { text: "Little eyes learn from little moments.", author: "Original" },
  { text: "Your tone becomes their inner voice.", author: "Original" },
  { text: "Routines are hugs on the calendar.", author: "Original" },
  { text: "Kids need roots and wings.", author: "Original" },
  { text: "Hold the phone after you hold the hand.", author: "Original" },
  { text: "Read the story before correcting the grammar.", author: "Original" },
  { text: "Be tough on standards, soft on people.", author: "Original" },
  { text: "Love listens before it solves.", author: "Original" },
  { text: "Love makes room for repair.", author: "Original" },
  { text: "Grace is strength with manners.", author: "Original" },
  { text: "Apologies are bridges you build yourself.", author: "Original" },
  { text: "Patience is parental superpower.", author: "Original" },
  { text: "Protect the room, not the point.", author: "Original" },
  { text: "Love chooses presence over performance.", author: "Original" },
  { text: "Teach by doing and narrating.", author: "Original" },
  { text: "Catch them doing it right.", author: "Original" },
  { text: "Small traditions make big memories.", author: "Original" },
  { text: "Your presence is the plan.", author: "Original" },
  { text: "Prototype your opinions.", author: "Original" },
  { text: "Constraints are invitations.", author: "Original" },
  { text: "Simplicity survives contact with reality.", author: "Original" },
  { text: "Elegant is when nothing can be removed.", author: "Original" },
  { text: "Prototype the risky parts first.", author: "Original" },
  { text: "Ship early, learn faster.", author: "Original" },
  { text: "Version one teaches version two.", author: "Original" },
  { text: "Make it simple, then obvious.", author: "Original" },
  { text: "Delight is in the details.", author: "Original" },
  { text: "Documentation is part of the product.", author: "Original" },
  { text: "If it’s manual twice, automate once.", author: "Original" },
  { text: "Write code for the reader.", author: "Original" },
  { text: "Tests protect tomorrow.", author: "Original" },
  { text: "Naming is design in words.", author: "Original" },
  { text: "Logs are love letters from your code.", author: "Original" },
  { text: "Read the error; it’s trying to help.", author: "Original" },
  { text: "Kill your darlings kindly.", author: "Original" },
  { text: "A small yes beats a huge maybe.", author: "Original" },
  { text: "Less to maintain, more to love.", author: "Original" },
  { text: "Clarity creates speed.", author: "Original" },
  { text: "Inputs you control; outputs you influence.", author: "Original" },
  { text: "Decide once; execute often.", author: "Original" },
  { text: "Plan in pencil; commit in ink.", author: "Original" },
  { text: "Strategy is choosing what not to do.", author: "Original" },
  { text: "Direction before speed.", author: "Original" },
  { text: "Focus is saying no nicely.", author: "Original" },
  { text: "Where focus goes, momentum grows.", author: "Original" },
  { text: "If it matters weekly, block it daily.", author: "Original" },
  { text: "Win the morning; don’t lose the night.", author: "Original" },
  { text: "Saying yes to everything says no to excellence.", author: "Original" },
  { text: "Make the right thing the easy thing.", author: "Original" },
  { text: "Environment beats willpower.", author: "Original" },
  { text: "Systems save willpower.", author: "Original" },
  { text: "Order reduces friction.", author: "Original" },
  { text: "Default to generosity.", author: "Original" },
  { text: "Short meetings reward preparation.", author: "Original" },
  { text: "Asynchronous is kind to deep work.", author: "Original" },
  { text: "Deep work dislikes open tabs.", author: "Original" },
  { text: "Great days start the night before.", author: "Original" },
  { text: "Notes are external RAM.", author: "Original" },
  { text: "Relentless rests, then returns.", author: "Original" },
  { text: "Relentless says ‘again’.", author: "Original" },
  { text: "Relentless is patient and prepared.", author: "Original" },
  { text: "Relentless keeps its promises to future you.", author: "Original" },
  { text: "Relentless does reps when watched and when not.", author: "Original" },
  { text: "Relentless forgives itself and continues.", author: "Original" },
  { text: "Relentless treats obstacles as practice.", author: "Original" },
  { text: "Relentless is calm under pressure.", author: "Original" },
  { text: "Relentless is kind to the clerk.", author: "Original" },
  { text: "Relentless chooses growth over comfort.", author: "Original" },
  { text: "Relentless starts when motivation ends.", author: "Original" },
  { text: "Relentless is a habit, not a mood.", author: "Original" },
  { text: "Relentless adds one more honest rep.", author: "Original" },
  { text: "Relentless turns setbacks into setup.", author: "Original" },
  { text: "Relentless measures in decades, acts in days.", author: "Original" },
  { text: "Relentless moves quiet and steady.", author: "Original" },
  { text: "Relentless edits excuses into action.", author: "Original" },
  { text: "Relentless trains for headwinds.", author: "Original" },
  { text: "Relentless is humble and hungry.", author: "Original" },
  { text: "Relentless remembers the why.", author: "Original" },
  { text: "Respect your morning every day.", author: "Original" },
  { text: "Automate deep work with less noise.", author: "Original" },
  { text: "Write your evening and make it sustainable.", author: "Original" },
  { text: "Build quality and make it sustainable.", author: "Original" },
  { text: "Start feedback until it looks easy.", author: "Original" },
  { text: "Measure your character especially on hard days.", author: "Original" },
  { text: "Protect your attention with patience.", author: "Original" },
  { text: "Write the long game and write it down.", author: "Original" },
  { text: "Protect feedback with patience.", author: "Original" },
  { text: "Refactor the next step and keep your promises.", author: "Original" },
  { text: "Simplify your character with less noise.", author: "Original" },
  { text: "Seek the constraint one brick at a time.", author: "Original" },
  { text: "Listen practice every day.", author: "Original" },
  { text: "Prototype systems with kindness.", author: "Original" },
  { text: "Refactor your character on purpose.", author: "Original" },
  { text: "Teach your evening with patience.", author: "Original" },
  { text: "Persist simplicity on purpose.", author: "Original" },
  { text: "Build your attention like it matters—because it does.", author: "Original" },
  { text: "Build what matters for future you.", author: "Original" },
  { text: "Schedule deep work especially on hard days.", author: "Original" },
  { text: "Automate your calendar and remove what you don’t need.", author: "Original" },
  { text: "Build your boundaries until it looks easy.", author: "Original" },
  { text: "Simplify honest work and show up again tomorrow.", author: "Original" },
  { text: "Schedule practice for future you.", author: "Original" },
  { text: "Measure the craft and keep your promises.", author: "Original" },
  { text: "Choose the process and forgive the detours.", author: "Original" },
  { text: "Write simplicity without drama.", author: "Original" },
  { text: "Choose practice with less noise.", author: "Original" },
  { text: "Focus your morning like it matters—because it does.", author: "Original" },
  { text: "Teach your calendar and show up again tomorrow.", author: "Original" },
  { text: "Clarify what matters with kindness.", author: "Original" },
  { text: "Nurture what matters with patience.", author: "Original" },
  { text: "Distill deep work and keep your promises.", author: "Original" },
  { text: "Finish quality and show up again tomorrow.", author: "Original" },
  { text: "Choose the why and show up again tomorrow.", author: "Original" },
  { text: "Make feedback and make it sustainable.", author: "Original" },
  { text: "Write your word and edit until it’s clear.", author: "Original" },
  { text: "Favor deep work and show up again tomorrow.", author: "Original" },
  { text: "Refactor feedback with less noise.", author: "Original" },
  { text: "Distill useful habits and keep the standard.", author: "Original" },
  { text: "Prototype the process with less noise.", author: "Original" },
  { text: "Clarify the process on purpose.", author: "Original" },
  { text: "Favor deep work until it looks easy.", author: "Original" },
  { text: "Design the constraint and keep your promises.", author: "Original" },
  { text: "Guard the craft and show up again tomorrow.", author: "Original" },
  { text: "Allow your boundaries and show up again tomorrow.", author: "Original" },
  { text: "Seek your evening one brick at a time.", author: "Original" },
  { text: "Keep small wins and make it sustainable.", author: "Original" },
  { text: "Simplify feedback one brick at a time.", author: "Original" },
  { text: "Automate the constraint and let the results talk.", author: "Original" },
  { text: "Start the constraint like it matters—because it does.", author: "Original" },
  { text: "Nurture small wins when no one is watching.", author: "Original" },
  { text: "Accept your energy until it looks easy.", author: "Original" },
  { text: "Prototype the process before it’s urgent.", author: "Original" },
  { text: "Keep the next step with kindness.", author: "Original" },
  { text: "Listen quality and let the results talk.", author: "Original" },
  { text: "Schedule your attention like it matters—because it does.", author: "Original" },
  { text: "Favor the why and edit until it’s clear.", author: "Original" },
  { text: "Accept deep work and remove what you don’t need.", author: "Original" },
  { text: "Focus the basics and forgive the detours.", author: "Original" },
  { text: "Automate your morning and forgive the detours.", author: "Original" },
  { text: "Start feedback and keep the standard.", author: "Original" },
  { text: "Teach simplicity and show up again tomorrow.", author: "Original" },
  { text: "Guard your morning without drama.", author: "Original" },
  { text: "Chase your word and edit until it’s clear.", author: "Original" },
  { text: "Protect patience and make it sustainable.", author: "Original" },
  { text: "Teach the long game and keep the standard.", author: "Original" },
  { text: "Make the long game before it’s urgent.", author: "Original" },
  { text: "Focus the next step without drama.", author: "Original" },
  { text: "Clarify the next step and celebrate small progress.", author: "Original" },
  { text: "Schedule the craft when no one is watching.", author: "Original" },
  { text: "Nurture simplicity with kindness.", author: "Original" },
  { text: "Simplify simplicity and celebrate small progress.", author: "Original" },
  { text: "Finish the basics and write it down.", author: "Original" },
  { text: "Guard your energy every day.", author: "Original" },
  { text: "Build what matters without drama.", author: "Original" },
  { text: "Write the process with less noise.", author: "Original" },
  { text: "Start the constraint until it looks easy.", author: "Original" },
  { text: "Choose patience and keep going.", author: "Original" },
  { text: "Clarify your attention and keep the standard.", author: "Original" },
  { text: "Simplify simplicity when no one is watching.", author: "Original" },
  { text: "Keep quality and keep going.", author: "Original" },
  { text: "Persist feedback with kindness.", author: "Original" },
  { text: "Teach the long game and write it down.", author: "Original" },
  { text: "Chase the craft and remove what you don’t need.", author: "Original" },
  { text: "Prototype patience and keep your promises.", author: "Original" },
  { text: "Design kindness without drama.", author: "Original" },
  { text: "Favor quality and show up again tomorrow.", author: "Original" },
  { text: "Nurture your calendar and celebrate small progress.", author: "Original" },
  { text: "Seek your morning with less noise.", author: "Original" },
  { text: "Write your attention on purpose.", author: "Original" },
  { text: "Protect the constraint and remove what you don’t need.", author: "Original" },
  { text: "Write the constraint with less noise.", author: "Original" },
  { text: "Protect your attention and keep your promises.", author: "Original" },
  { text: "Respect the process with less noise.", author: "Original" },
  { text: "Choose the process on purpose.", author: "Original" },
  { text: "Choose the long game with less noise.", author: "Original" },
  { text: "Teach quality and keep going.", author: "Original" },
  { text: "Design feedback when no one is watching.", author: "Original" },
  { text: "Automate the constraint and make it obvious.", author: "Original" },
  { text: "Allow small wins and keep going.", author: "Original" },
  { text: "Listen your character with patience.", author: "Original" },
  { text: "Build your morning and forgive the detours.", author: "Original" },
  { text: "Chase what matters and let the results talk.", author: "Original" },
  { text: "Chase your calendar and make it sustainable.", author: "Original" },
  { text: "Practice quality and show up again tomorrow.", author: "Original" },
  { text: "Respect your morning especially on hard days.", author: "Original" },
  { text: "Favor patience on purpose.", author: "Original" },
  { text: "Listen practice before it’s urgent.", author: "Original" },
  { text: "Write the craft with patience.", author: "Original" },
  { text: "Simplify your calendar when no one is watching.", author: "Original" },
  { text: "Chase your word one brick at a time.", author: "Original" },
  { text: "Seek small wins until it looks easy.", author: "Original" },
  { text: "Seek systems and remove what you don’t need.", author: "Original" },
  { text: "Build the process and show up again tomorrow.", author: "Original" },
  { text: "Simplify momentum every day.", author: "Original" },
  { text: "Choose simplicity with less noise.", author: "Original" },
  { text: "Make your character and keep going.", author: "Original" },
  { text: "Allow the craft like it matters—because it does.", author: "Original" },
  { text: "Start the process with kindness.", author: "Original" },
  { text: "Favor the basics like it matters—because it does.", author: "Original" },
  { text: "Teach systems and edit until it’s clear.", author: "Original" },
  { text: "Train your character and keep your promises.", author: "Original" },
  { text: "Persist patience and remove what you don’t need.", author: "Original" },
  { text: "Distill kindness and keep going.", author: "Original" },
  { text: "Keep the craft without drama.", author: "Original" },
  { text: "Design the process and make it obvious.", author: "Original" },
  { text: "Automate feedback especially on hard days.", author: "Original" },
  { text: "Automate useful habits especially on hard days.", author: "Original" },
  { text: "Practice the constraint and keep going.", author: "Original" },
  { text: "Accept practice and celebrate small progress.", author: "Original" },
  { text: "Make the process and celebrate small progress.", author: "Original" },
  { text: "Choose practice with kindness.", author: "Original" },
];