export type TimezoneOption = {
    id: number;
    label: string;
    tz: string;
    funFact?: {
        en: string;
        sp: string;
        pt: string;
    };
};

export const timezones: TimezoneOption[] = [
    // --- North America ---
    // United States
    { id: 1, label: 'New York', tz: 'America/New_York', funFact: { en: 'The first pizzeria in the United States opened in NYC in 1905.', sp: 'La primera pizzería de Estados Unidos abrió en Nueva York en 1905.', pt: 'A primeira pizzaria dos Estados Unidos foi inaugurada em Nova York em 1905.' } },
    { id: 2, label: 'Chicago', tz: 'America/Chicago', funFact: { en: 'The world\'s first skyscraper was built here in 1885.', sp: 'El primer rascacielos del mundo se construyó aquí en 1885.', pt: 'O primeiro arranha-céu do mundo foi construído aqui em 1885.' } },
    { id: 3, label: 'Denver', tz: 'America/Denver', funFact: { en: 'It is nicknamed the "Mile High City" because its official elevation is exactly one mile.', sp: 'Es apodada la "Ciudad de la Milla de Altura" porque su elevación oficial es exactamente de una milla.', pt: 'É apelidada de "Cidade de uma Milha de Altitude" porque sua elevação oficial é de exatamente uma milha.' } },
    { id: 4, label: 'Los Angeles', tz: 'America/Los_Angeles', funFact: { en: 'The iconic Hollywood sign originally read "Hollywoodland".', sp: 'El icónico letrero de Hollywood originalmente decía "Hollywoodland".', pt: 'O icônico letreiro de Hollywood originalmente dizia "Hollywoodland".' } },
    { id: 5, label: 'Anchorage', tz: 'America/Anchorage', funFact: { en: 'It is home to the world\'s busiest seaplane base.', sp: 'Alberga la base de hidroaviones más concurrida del mundo.', pt: 'É o lar da base de hidroaviões mais movimentada do mundo.' } },
    { id: 6, label: 'Honolulu', tz: 'Pacific/Honolulu', funFact: { en: 'Iolani Palace in Honolulu is the only official royal palace in the United States.', sp: 'El Palacio Iolani en Honolulu es el único palacio real oficial en los Estados Unidos.', pt: 'O Palácio Iolani em Honolulu é o único palácio real oficial nos Estados Unidos.' } },
    { id: 7, label: 'Phoenix', tz: 'America/Phoenix', funFact: { en: 'Greater Phoenix has more than 200 golf courses.', sp: 'El área metropolitana de Phoenix tiene más de 200 campos de golf.', pt: 'A Grande Phoenix tem mais de 200 campos de golfe.' } },
    { id: 62, label: 'Atlanta', tz: 'America/New_York', funFact: { en: 'It\'s home to the world\'s busiest airport, Hartsfield-Jackson Atlanta International.', sp: 'Alberga el aeropuerto más concurrido del mundo, Hartsfield-Jackson Atlanta International.', pt: 'É o lar do aeroporto mais movimentado do mundo, Hartsfield-Jackson Atlanta International.' } },
    { id: 63, label: 'Boston', tz: 'America/New_York', funFact: { en: 'The first subway system in the United States was built in Boston in 1897.', sp: 'El primer sistema de metro de Estados Unidos se construyó en Boston en 1897.', pt: 'O primeiro sistema de metrô dos Estados Unidos foi construído em Boston em 1897.' } },
    { id: 64, label: 'Miami', tz: 'America/New_York', funFact: { en: 'It has the largest collection of Art Deco architecture in the world.', sp: 'Tiene la mayor colección de arquitectura Art Deco del mundo.', pt: 'Possui a maior coleção de arquitetura Art Déco do mundo.' } },
    { id: 65, label: 'Washington D.C.', tz: 'America/New_York', funFact: { en: 'The Library of Congress is the largest library in the world.', sp: 'La Biblioteca del Congreso es la biblioteca más grande del mundo.', pt: 'A Biblioteca do Congresso é a maior biblioteca do mundo.' } },
    { id: 66, label: 'Dallas', tz: 'America/Chicago', funFact: { en: 'The frozen margarita machine was invented in Dallas.', sp: 'La máquina de margarita congelada fue inventada en Dallas.', pt: 'A máquina de margarita congelada foi inventada em Dallas.' } },
    { id: 67, label: 'Houston', tz: 'America/Chicago', funFact: { en: 'The first word spoken from the moon was "Houston".', sp: 'La primera palabra pronunciada desde la luna fue "Houston".', pt: 'A primeira palavra dita da lua foi "Houston".' } },
    { id: 68, label: 'New Orleans', tz: 'America/Chicago', funFact: { en: 'It is considered the birthplace of jazz music.', sp: 'Es considerada la cuna de la música jazz.', pt: 'É considerada o berço da música jazz.' } },
    { id: 69, label: 'Salt Lake City', tz: 'America/Denver', funFact: { en: 'The Great Salt Lake is up to 7 times saltier than the ocean.', sp: 'El Gran Lago Salado es hasta 7 veces más salado que el océano.', pt: 'O Grande Lago Salgado é até 7 vezes mais salgado que o oceano.' } },
    { id: 70, label: 'San Francisco', tz: 'America/Los_Angeles', funFact: { en: 'The fortune cookie was invented here by a Japanese immigrant.', sp: 'La galleta de la fortuna fue inventada aquí por un inmigrante japonés.', pt: 'O biscoito da sorte foi inventado aqui por um imigrante japonês.' } },
    { id: 71, label: 'Seattle', tz: 'America/Los_Angeles', funFact: { en: 'The original Starbucks was founded here in 1971.', sp: 'El Starbucks original se fundó aquí en 1971.', pt: 'A Starbucks original foi fundada aqui em 1971.' } },
    { id: 72, label: 'Las Vegas', tz: 'America/Los_Angeles', funFact: { en: 'The Las Vegas Strip is the brightest place on Earth when viewed from space.', sp: 'El Strip de Las Vegas es el lugar más brillante de la Tierra visto desde el espacio.', pt: 'A Las Vegas Strip é o lugar mais brilhante da Terra quando vista do espaço.' } },
    { id: 172, label: 'Orlando', tz: 'America/New_York', funFact: { en: 'It is known as the "Theme Park Capital of the World".', sp: 'Es conocida como la "Capital Mundial de los Parques Temáticos".', pt: 'É conhecida como a "Capital Mundial dos Parques Temáticos".' } },
    { id: 173, label: 'Grand Canyon', tz: 'America/Phoenix', funFact: { en: 'The Grand Canyon is home to a unique pink rattlesnake.', sp: 'El Gran Cañón alberga una serpiente de cascabel rosa única.', pt: 'O Grand Canyon é o lar de uma cascavel rosa única.' } },
    { id: 205, label: 'Philadelphia', tz: 'America/New_York', funFact: { en: 'It was the first World Heritage City in the United States.', sp: 'Fue la primera Ciudad Patrimonio de la Humanidad en los Estados Unidos.', pt: 'Foi a primeira Cidade Patrimônio Mundial nos Estados Unidos.' } },
    // US States & Regions
    { id: 107, label: 'California', tz: 'America/Los_Angeles', funFact: { en: 'If it were a country, its economy would be the 5th largest in the world.', sp: 'Si fuera un país, su economía sería la quinta más grande del mundo.', pt: 'Se fosse um país, sua economia seria a 5ª maior do mundo.' } },
    { id: 108, label: 'Texas', tz: 'America/Chicago', funFact: { en: 'It\'s the only state to have the flags of 6 different nations fly over it.', sp: 'Es el único estado que ha tenido las banderas de 6 naciones diferentes ondeando sobre él.', pt: 'É o único estado a ter as bandeiras de 6 nações diferentes hasteadas sobre ele.' } },
    { id: 109, label: 'Florida', tz: 'America/New_York', funFact: { en: 'It is the only state that has an embassy (in Washington D.C.).', sp: 'Es el único estado que tiene una embajada (en Washington D.C.).', pt: 'É o único estado que tem uma embaixada (em Washington D.C.).' } },
    { id: 110, label: 'Arizona', tz: 'America/Phoenix', funFact: { en: 'It\'s the only state where it is illegal for a donkey to sleep in a bathtub.', sp: 'Es el único estado donde es ilegal que un burro duerma en una bañera.', pt: 'É o único estado onde é ilegal um burro dormir numa banheira.' } },
    { id: 111, label: 'Colorado', tz: 'America/Denver', funFact: { en: 'The 13th step of the state capital building is exactly one mile above sea level.', sp: 'El escalón número 13 del capitolio estatal está exactamente a una milla sobre el nivel del mar.', pt: 'O 13º degrau do capitólio estadual está exatamente a uma milha acima do nível do mar.' } },
    { id: 112, label: 'Illinois', tz: 'America/Chicago', funFact: { en: 'The state slogan is "Land of Lincoln" as Abraham Lincoln started his political career here.', sp: 'El lema del estado es "Tierra de Lincoln", ya que Abraham Lincoln comenzó su carrera política aquí.', pt: 'O lema do estado é "Terra de Lincoln", pois Abraham Lincoln começou sua carreira política aqui.' } },

    // Canada
    { id: 8, label: 'Toronto', tz: 'America/Toronto', funFact: { en: 'The Toronto Zoo is the largest in Canada, housing over 5,000 animals.', sp: 'El Zoológico de Toronto es el más grande de Canadá, con más de 5,000 animales.', pt: 'O Zoológico de Toronto é o maior do Canadá, abrigando mais de 5.000 animais.' } },
    { id: 9, label: 'Vancouver', tz: 'America/Vancouver', funFact: { en: 'It\'s often called "Hollywood North" for its booming film industry.', sp: 'A menudo se le llama "Hollywood del Norte" por su próspera industria cinematográfica.', pt: 'É frequentemente chamada de "Hollywood do Norte" por sua próspera indústria cinematográfica.' } },
    { id: 10, label: 'Halifax', tz: 'America/Halifax', funFact: { en: 'It has one of the world\'s longest natural harbors.', sp: 'Tiene uno de los puertos naturales más largos del mundo.', pt: 'Possui um dos maiores portos naturais do mundo.' } },
    { id: 11, label: 'Winnipeg', tz: 'America/Winnipeg', funFact: { en: 'The city is the birthplace of the character Winnie the Pooh.', sp: 'La ciudad es el lugar de nacimiento del personaje Winnie the Pooh.', pt: 'A cidade é o berço do personagem Winnie the Pooh.' } },
    { id: 73, label: 'Montreal', tz: 'America/Toronto', funFact: { en: 'It\'s the second-largest French-speaking city in the world after Paris.', sp: 'Es la segunda ciudad de habla francesa más grande del mundo después de París.', pt: 'É a segunda maior cidade de língua francesa do mundo, depois de Paris.' } },
    { id: 74, label: 'Ottawa', tz: 'America/Toronto', funFact: { en: 'The Rideau Canal becomes the world\'s largest skating rink in winter.', sp: 'El Canal Rideau se convierte en la pista de patinaje más grande del mundo en invierno.', pt: 'O Canal Rideau se torna a maior pista de patinação do mundo no inverno.' } },
    { id: 75, label: 'Calgary', tz: 'America/Edmonton', funFact: { en: 'The Caesar cocktail was invented here in 1969.', sp: 'El cóctel Caesar fue inventado aquí en 1969.', pt: 'O coquetel Caesar foi inventado aqui em 1969.' } },
    { id: 76, label: 'Edmonton', tz: 'America/Edmonton', funFact: { en: 'It is home to North America\'s largest mall, the West Edmonton Mall.', sp: 'Alberga el centro comercial más grande de América del Norte, el West Edmonton Mall.', pt: 'É o lar do maior shopping da América do Norte, o West Edmonton Mall.' } },
    { id: 174, label: 'Banff', tz: 'America/Edmonton', funFact: { en: 'Banff National Park is Canada\'s oldest national park.', sp: 'El Parque Nacional Banff es el parque nacional más antiguo de Canadá.', pt: 'O Parque Nacional de Banff é o parque nacional mais antigo do Canadá.' } },
    // Canadian Provinces
    { id: 113, label: 'Ontario', tz: 'America/Toronto', funFact: { en: 'It is home to about one-third of the world\'s freshwater.', sp: 'Alberga aproximadamente un tercio del agua dulce del mundo.', pt: 'É o lar de cerca de um terço da água doce do mundo.' } },
    { id: 114, label: 'Quebec', tz: 'America/Toronto', funFact: { en: 'It is the only province whose official language is French.', sp: 'Es la única provincia cuyo idioma oficial es el francés.', pt: 'É a única província cuja língua oficial é o francês.' } },
    { id: 115, label: 'British Columbia', tz: 'America/Vancouver', funFact: { en: 'It has the longest coastline of any province in Canada.', sp: 'Tiene la costa más larga de todas las provincias de Canadá.', pt: 'Possui a costa mais longa de qualquer província do Canadá.' } },
    { id: 116, label: 'Alberta', tz: 'America/Edmonton', funFact: { en: 'It is the only Canadian province that is rat-free.', sp: 'Es la única provincia canadiense libre de ratas.', pt: 'É a única província canadense livre de ratos.' } },

    // Mexico
    { id: 12, label: 'Mexico City', tz: 'America/Mexico_City', funFact: { en: 'It was built on a lake, and it sinks about 6 to 8 inches a year.', sp: 'Fue construida sobre un lago y se hunde de 6 a 8 pulgadas al año.', pt: 'Foi construída sobre um lago e afunda cerca de 15 a 20 centímetros por ano.' } },
    { id: 13, label: 'Cancun', tz: 'America/Cancun', funFact: { en: 'It is home to an underwater museum with over 500 sculptures.', sp: 'Alberga un museo submarino con más de 500 esculturas.', pt: 'É o lar de um museu subaquático com mais de 500 esculturas.' } },
    { id: 77, label: 'Tijuana', tz: 'America/Tijuana', funFact: { en: 'The Caesar salad was invented in Tijuana.', sp: 'La ensalada César fue inventada en Tijuana.', pt: 'A salada Caesar foi inventada em Tijuana.' } },
    { id: 175, label: 'Guadalajara', tz: 'America/Mexico_City', funFact: { en: 'It is the birthplace of both mariachi music and tequila.', sp: 'Es la cuna tanto de la música mariachi como del tequila.', pt: 'É o berço tanto da música mariachi quanto da tequila.' } },
    { id: 123, label: 'Mexico', tz: 'America/Mexico_City', funFact: { en: 'It is home to the world\'s largest pyramid, the Great Pyramid of Cholula.', sp: 'Alberga la pirámide más grande del mundo, la Gran Pirámide de Cholula.', pt: 'É o lar da maior pirâmide do mundo, a Grande Pirâmide de Cholula.' } },

    // --- South America ---
    // Peru
    { id: 14, label: 'Lima', tz: 'America/Lima', funFact: { en: 'It is the second-largest desert city in the world, after Cairo.', sp: 'Es la segunda ciudad desértica más grande del mundo, después de El Cairo.', pt: 'É a segunda maior cidade desértica do mundo, depois do Cairo.' } },
    { id: 176, label: 'Cusco', tz: 'America/Lima', funFact: { en: 'The city is shaped like a puma, a sacred animal in Inca culture.', sp: 'La ciudad tiene forma de puma, un animal sagrado en la cultura inca.', pt: 'A cidade tem a forma de um puma, um animal sagrado na cultura inca.' } },
    { id: 220, label: 'Arequipa', tz: 'America/Lima', funFact: { en: 'Its historic center is built from a white volcanic rock, earning it the nickname "The White City".', sp: 'Su centro histórico está construido con una roca volcánica blanca, lo que le valió el apodo de "La Ciudad Blanca".', pt: 'Seu centro histórico é construído com uma rocha vulcânica branca, o que lhe rendeu o apelido de "A Cidade Branca".' } },
    { id: 124, label: 'Peru', tz: 'America/Lima', funFact: { en: 'The potato is originally from Peru; there are over 3,000 varieties.', sp: 'La papa es originaria de Perú; existen más de 3,000 variedades.', pt: 'A batata é originária do Peru; existem mais de 3.000 variedades.' } },
    // Argentina
    { id: 15, label: 'Buenos Aires', tz: 'America/Argentina/Buenos_Aires', funFact: { en: 'It has the most bookstores per person of any city in the world.', sp: 'Tiene la mayor cantidad de librerías por persona de cualquier ciudad del mundo.', pt: 'Possui o maior número de livrarias por pessoa de qualquer cidade do mundo.' } },
    { id: 177, label: 'Ushuaia', tz: 'America/Argentina/Buenos_Aires', funFact: { en: 'It is the southernmost city in the world, often called the "End of the World".', sp: 'Es la ciudad más austral del mundo, a menudo llamada el "Fin del Mundo".', pt: 'É a cidade mais ao sul do mundo, muitas vezes chamada de "Fim do Mundo".' } },
    { id: 125, label: 'Argentina', tz: 'America/Argentina/Buenos_Aires', funFact: { en: 'The Tango dance originated in the slaughterhouse districts of Buenos Aires.', sp: 'El tango se originó en los barrios de los mataderos de Buenos Aires.', pt: 'O tango originou-se nos distritos de matadouros de Buenos Aires.' } },
    // Brazil
    { id: 16, label: 'São Paulo', tz: 'America/Sao_Paulo', funFact: { en: 'It has the largest Japanese population outside of Japan.', sp: 'Tiene la mayor población japonesa fuera de Japón.', pt: 'Possui a maior população japonesa fora do Japão.' } },
    { id: 17, label: 'Rio de Janeiro', tz: 'America/Sao_Paulo', funFact: { en: 'The Christ the Redeemer statue is one of the New Seven Wonders of the World.', sp: 'La estatua del Cristo Redentor es una de las Nuevas Siete Maravillas del Mundo.', pt: 'A estátua do Cristo Redentor é uma das Novas Sete Maravilhas do Mundo.' } },
    { id: 178, label: 'Salvador', tz: 'America/Sao_Paulo', funFact: { en: 'It was the first capital of Brazil.', sp: 'Fue la primera capital de Brasil.', pt: 'Foi a primeira capital do Brasil.' } },
    { id: 78, label: 'Brasília', tz: 'America/Sao_Paulo', funFact: { en: 'The city is shaped like an airplane when viewed from above.', sp: 'La ciudad tiene forma de avión vista desde arriba.', pt: 'A cidade tem a forma de um avião quando vista de cima.' } },
    { id: 126, label: 'Brazil', tz: 'America/Sao_Paulo', funFact: { en: 'Brazil is the world\'s largest exporter of coffee.', sp: 'Brasil es el mayor exportador de café del mundo.', pt: 'O Brasil é o maior exportador de café do mundo.' } },
    // Chile
    { id: 18, label: 'Santiago', tz: 'America/Santiago', funFact: { en: 'It has the tallest building in Latin America, the Gran Torre Santiago.', sp: 'Tiene el edificio más alto de América Latina, la Gran Torre Santiago.', pt: 'Possui o edifício mais alto da América Latina, a Gran Torre Santiago.' } },
    { id: 179, label: 'Valparaíso', tz: 'America/Santiago', funFact: { en: 'The entire city is a UNESCO World Heritage site.', sp: 'La ciudad entera es Patrimonio de la Humanidad por la UNESCO.', pt: 'A cidade inteira é um Patrimônio Mundial da UNESCO.' } },
    { id: 127, label: 'Chile', tz: 'America/Santiago', funFact: { en: 'The Atacama Desert is the driest place on Earth.', sp: 'El desierto de Atacama es el lugar más seco de la Tierra.', pt: 'O Deserto do Atacama é o lugar mais seco da Terra.' } },
    // Colombia
    { id: 19, label: 'Bogotá', tz: 'America/Bogota', funFact: { en: 'It has the world\'s largest network of bicycle paths, called "Ciclovías".', sp: 'Tiene la red de ciclovías más grande del mundo, llamada "Ciclovías".', pt: 'Possui a maior rede de ciclovias do mundo, chamada "Ciclovías".' } },
    { id: 180, label: 'Cartagena', tz: 'America/Bogota', funFact: { en: 'Its colonial walled city and fortress are a UNESCO World Heritage site.', sp: 'Su ciudad amurallada colonial y su fortaleza son Patrimonio de la Humanidad por la UNESCO.', pt: 'Sua cidade murada colonial e fortaleza são um Patrimônio Mundial da UNESCO.' } },
    { id: 207, label: 'Medellín', tz: 'America/Bogota', funFact: { en: 'Known as the "City of Eternal Spring" for its pleasant year-round climate.', sp: 'Conocida como la "Ciudad de la Eterna Primavera" por su agradable clima durante todo el año.', pt: 'Conhecida como a "Cidade da Eterna Primavera" por seu clima agradável durante todo o ano.' } },
    { id: 128, label: 'Colombia', tz: 'America/Bogota', funFact: { en: 'It is the world\'s leading source of emeralds.', sp: 'Es la principal fuente de esmeraldas del mundo.', pt: 'É a principal fonte de esmeraldas do mundo.' } },
    // Venezuela
    { id: 20, label: 'Caracas', tz: 'America/Caracas', funFact: { en: 'It is home to the world\'s highest waterfall, Angel Falls.', sp: 'Alberga la cascada más alta del mundo, el Salto Ángel.', pt: 'É o lar da cachoeira mais alta do mundo, o Salto Ángel.' } },
    { id: 129, label: 'Venezuela', tz: 'America/Caracas', funFact: { en: 'The country was named after Venice, Italy.', sp: 'El país fue nombrado en honor a Venecia, Italia.', pt: 'O país foi nomeado em homenagem a Veneza, Itália.' } },
    // Bolivia
    { id: 21, label: 'La Paz', tz: 'America/La_Paz', funFact: { en: 'It is the highest administrative capital in the world.', sp: 'Es la capital administrativa más alta del mundo.', pt: 'É a capital administrativa mais alta do mundo.' } },
    { id: 130, label: 'Bolivia', tz: 'America/La_Paz', funFact: { en: 'The Salar de Uyuni is the world\'s largest salt flat.', sp: 'El Salar de Uyuni es el salar más grande del mundo.', pt: 'O Salar de Uyuni é o maior deserto de sal do mundo.' } },
    // Uruguay
    { id: 79, label: 'Montevideo', tz: 'America/Montevideo', funFact: { en: 'It is considered the safest capital city in Latin America.', sp: 'Es considerada la capital más segura de América Latina.', pt: 'É considerada a capital mais segura da América Latina.' } },
    { id: 131, label: 'Uruguay', tz: 'America/Montevideo', funFact: { en: 'It was the first country in the world to fully legalize cannabis.', sp: 'Fue el primer país del mundo en legalizar completamente el cannabis.', pt: 'Foi o primeiro país do mundo a legalizar totalmente a cannabis.' } },
    // Ecuador
    { id: 80, label: 'Quito', tz: 'America/Guayaquil', funFact: { en: 'It was the first city to be declared a UNESCO World Heritage site.', sp: 'Fue la primera ciudad declarada Patrimonio de la Humanidad por la UNESCO.', pt: 'Foi a primeira cidade a ser declarada Patrimônio Mundial da UNESCO.' } },
    { id: 132, label: 'Ecuador', tz: 'America/Guayaquil', funFact: { en: 'It is named after the Equator, which runs through the country.', sp: 'Lleva el nombre del Ecuador, que atraviesa el país.', pt: 'É nomeado após o Equador, que atravessa o país.' } },

    // --- Europe ---
    // United Kingdom
    { id: 22, label: 'London', tz: 'Europe/London', funFact: { en: 'Over 300 languages are spoken in London, more than any other city in the world.', sp: 'En Londres se hablan más de 300 idiomas, más que en cualquier otra ciudad del mundo.', pt: 'Mais de 300 idiomas são falados em Londres, mais do que em qualquer outra cidade do mundo.' } },
    { id: 81, label: 'Manchester', tz: 'Europe/London', funFact: { en: 'The first professional football league in the world was founded here.', sp: 'La primera liga de fútbol profesional del mundo se fundó aquí.', pt: 'A primeira liga de futebol profissional do mundo foi fundada aqui.' } },
    { id: 82, label: 'Edinburgh', tz: 'Europe/London', funFact: { en: 'It was the first city in the world to have its own fire brigade.', sp: 'Fue la primera ciudad del mundo en tener su propio cuerpo de bomberos.', pt: 'Foi a primeira cidade do mundo a ter sua própria brigada de incêndio.' } },
    { id: 181, label: 'Stonehenge', tz: 'Europe/London', funFact: { en: 'The stones were transported from over 150 miles away.', sp: 'Las piedras fueron transportadas desde más de 150 millas de distancia.', pt: 'As pedras foram transportadas de mais de 240 quilômetros de distância.' } },
    { id: 117, label: 'England', tz: 'Europe/London', funFact: { en: 'The world\'s oldest zoo is in London.', sp: 'El zoológico más antiguo del mundo se encuentra en Londres.', pt: 'O zoológico mais antigo do mundo fica em Londres.' } },
    { id: 118, label: 'Scotland', tz: 'Europe/London', funFact: { en: 'The unicorn is the official national animal of Scotland.', sp: 'El unicornio es el animal nacional oficial de Escocia.', pt: 'O unicórnio é o animal nacional oficial da Escócia.' } },
    { id: 134, label: 'United Kingdom', tz: 'Europe/London', funFact: { en: 'There are more chickens than people in the UK.', sp: 'Hay más pollos que personas en el Reino Unido.', pt: 'Existem mais galinhas do que pessoas no Reino Unido.' } },
    // Ireland
    { id: 23, label: 'Dublin', tz: 'Europe/Dublin', funFact: { en: 'Dublin\'s O\'Connell Bridge is the only bridge in Europe that is wider than it is long.', sp: 'El puente O\'Connell de Dublín es el único puente de Europa que es más ancho que largo.', pt: 'A Ponte O\'Connell de Dublin é a única ponte na Europa que é mais larga do que longa.' } },
    { id: 133, label: 'Ireland', tz: 'Europe/Dublin', funFact: { en: 'Halloween originated in Ireland from the ancient Celtic festival of Samhain.', sp: 'Halloween se originó en Irlanda a partir del antiguo festival celta de Samhain.', pt: 'O Halloween originou-se na Irlanda a partir do antigo festival celta de Samhain.' } },
    // France
    { id: 24, label: 'Paris', tz: 'Europe/Paris', funFact: { en: 'The Eiffel Tower was originally intended to be a temporary structure.', sp: 'La Torre Eiffel fue originalmente concebida como una estructura temporal.', pt: 'A Torre Eiffel foi originalmente planejada para ser uma estrutura temporária.' } },
    { id: 182, label: 'Nice', tz: 'Europe/Paris', funFact: { en: 'It has the second-most museums in France after Paris.', sp: 'Es la segunda ciudad con más museos de Francia, después de París.', pt: 'É a segunda cidade com mais museus na França, depois de Paris.' } },
    { id: 135, label: 'France', tz: 'Europe/Paris', funFact: { en: 'It is the most visited country in the world.', sp: 'Es el país más visitado del mundo.', pt: 'É o país mais visitado do mundo.' } },
    // Germany
    { id: 25, label: 'Berlin', tz: 'Europe/Berlin', funFact: { en: 'Berlin has more bridges than Venice.', sp: 'Berlín tiene más puentes que Venecia.', pt: 'Berlim tem mais pontes do que Veneza.' } },
    { id: 83, label: 'Munich', tz: 'Europe/Berlin', funFact: { en: 'Oktoberfest is actually held in September.', sp: 'El Oktoberfest en realidad se celebra en septiembre.', pt: 'A Oktoberfest na verdade é realizada em setembro.' } },
    { id: 84, label: 'Hamburg', tz: 'Europe/Berlin', funFact: { en: 'It has the world\'s largest model railway, Miniatur Wunderland.', sp: 'Tiene la maqueta de tren más grande del mundo, Miniatur Wunderland.', pt: 'Possui a maior maquete ferroviária do mundo, a Miniatur Wunderland.' } },
    { id: 183, label: 'Neuschwanstein Castle', tz: 'Europe/Berlin', funFact: { en: 'This castle was the inspiration for Disney\'s Sleeping Beauty castle.', sp: 'Este castillo fue la inspiración para el castillo de la Bella Durmiente de Disney.', pt: 'Este castelo foi a inspiração para o castelo da Bela Adormecida da Disney.' } },
    { id: 206, label: 'Frankfurt', tz: 'Europe/Berlin', funFact: { en: 'The name "hamburger" is believed to have originated from this city.', sp: 'Se cree que el nombre "hamburguesa" se originó en esta ciudad.', pt: 'Acredita-se que o nome "hambúrguer" tenha se originado nesta cidade.' } },
    { id: 136, label: 'Germany', tz: 'Europe/Berlin', funFact: { en: 'There are over 1,500 different types of beer brewed in Germany.', sp: 'En Alemania se elaboran más de 1.500 tipos diferentes de cerveza.', pt: 'Existem mais de 1.500 tipos diferentes de cerveja produzidos na Alemanha.' } },
    // Spain
    { id: 26, label: 'Madrid', tz: 'Europe/Madrid', funFact: { en: 'It is the highest capital city in the European Union.', sp: 'Es la capital más alta de la Unión Europea.', pt: 'É a capital mais alta da União Europeia.' } },
    { id: 85, label: 'Barcelona', tz: 'Europe/Madrid', funFact: { en: 'The Sagrada Familia has been under construction for over 140 years.', sp: 'La Sagrada Familia lleva más de 140 años en construcción.', pt: 'A Sagrada Família está em construção há mais de 140 anos.' } },
    { id: 184, label: 'Seville', tz: 'Europe/Madrid', funFact: { en: 'It is the birthplace of Flamenco dance.', sp: 'Es la cuna del baile flamenco.', pt: 'É o berço da dança flamenca.' } },
    { id: 209, label: 'Tenerife (Canary Islands)', tz: 'Atlantic/Canary', funFact: { en: 'It is home to the highest peak in Spain, Mount Teide.', sp: 'Alberga el pico más alto de España, el Teide.', pt: 'É o lar do pico mais alto da Espanha, o Monte Teide.' } },
    { id: 137, label: 'Spain', tz: 'Europe/Madrid', funFact: { en: 'Spain is the only country in Europe that shares a physical border with an African country (Morocco).', sp: 'España es el único país de Europa que comparte una frontera física con un país africano (Marruecos).', pt: 'A Espanha é o único país da Europa que partilha uma fronteira física com um país africano (Marrocos).' } },
    // Italy
    { id: 27, label: 'Rome', tz: 'Europe/Rome', funFact: { en: 'The Trevi Fountain collects about €3,000 every day, which is donated to charity.', sp: 'La Fontana de Trevi recauda unos 3.000 € al día, que se donan a obras de caridad.', pt: 'A Fontana di Trevi arrecada cerca de 3.000 € por dia, que são doados para caridade.' } },
    { id: 86, label: 'Milan', tz: 'Europe/Rome', funFact: { en: 'It is considered one of the "Big Four" fashion capitals of the world.', sp: 'Es considerada una de las "Cuatro Grandes" capitales de la moda del mundo.', pt: 'É considerada uma das "Quatro Grandes" capitais da moda do mundo.' } },
    { id: 185, label: 'Venice', tz: 'Europe/Rome', funFact: { en: 'It is sinking at a rate of about 1-2 millimeters per year.', sp: 'Se está hundiendo a un ritmo de 1-2 milímetros por año.', pt: 'Está afundando a uma taxa de cerca de 1-2 milímetros por ano.' } },
    { id: 186, label: 'Florence', tz: 'Europe/Rome', funFact: { en: 'It is considered the birthplace of the Renaissance.', sp: 'Es considerada la cuna del Renacimiento.', pt: 'É considerada o berço do Renascimento.' } },
    { id: 138, label: 'Italy', tz: 'Europe/Rome', funFact: { en: 'There are over 1,500 lakes in Italy.', sp: 'Hay más de 1.500 lagos en Italia.', pt: 'Existem mais de 1.500 lagos na Itália.' } },
    // Netherlands
    { id: 28, label: 'Amsterdam', tz: 'Europe/Amsterdam', funFact: { en: 'There are more bicycles than people in Amsterdam.', sp: 'Hay más bicicletas que personas en Ámsterdam.', pt: 'Existem mais bicicletas do que pessoas em Amsterdã.' } },
    { id: 139, label: 'Netherlands', tz: 'Europe/Amsterdam', funFact: { en: 'About a quarter of the country is below sea level.', sp: 'Aproximadamente una cuarta parte del país se encuentra por debajo del nivel del mar.', pt: 'Cerca de um quarto do país está abaixo do nível do mar.' } },
    // Norway
    { id: 29, label: 'Oslo', tz: 'Europe/Oslo', funFact: { en: 'The Nobel Peace Prize is awarded in Oslo each year.', sp: 'El Premio Nobel de la Paz se entrega en Oslo cada año.', pt: 'O Prêmio Nobel da Paz é concedido em Oslo todos os anos.' } },
    { id: 140, label: 'Norway', tz: 'Europe/Oslo', funFact: { en: 'Norway has the highest concentration of fjords in the world.', sp: 'Noruega tiene la mayor concentración de fiordos del mundo.', pt: 'A Noruega tem a maior concentração de fiordes do mundo.' } },
    // Sweden
    { id: 30, label: 'Stockholm', tz: 'Europe/Stockholm', funFact: { en: 'It is built on 14 islands, connected by 57 bridges.', sp: 'Está construida sobre 14 islas, conectadas por 57 puentes.', pt: 'É construída em 14 ilhas, conectadas por 57 pontes.' } },
    { id: 141, label: 'Sweden', tz: 'Europe/Stockholm', funFact: { en: 'It is the country with the most islands (over 221,800).', sp: 'Es el país con más islas (más de 221.800).', pt: 'É o país com o maior número de ilhas (mais de 221.800).' } },
    // Finland
    { id: 31, label: 'Helsinki', tz: 'Europe/Helsinki', funFact: { en: 'The tap water in Helsinki is among the purest in the world.', sp: 'El agua del grifo en Helsinki es una de las más puras del mundo.', pt: 'A água da torneira em Helsinque está entre as mais puras do mundo.' } },
    { id: 142, label: 'Finland', tz: 'Europe/Helsinki', funFact: { en: 'It is known as the "Land of a Thousand Lakes" (there are actually 187,888).', sp: 'Es conocido como la "Tierra de los Mil Lagos" (en realidad hay 187.888).', pt: 'É conhecida como a "Terra dos Mil Lagos" (na verdade, existem 187.888).' } },
    // Greece
    { id: 32, label: 'Athens', tz: 'Europe/Athens', funFact: { en: 'It is one of the oldest cities in the world, with a recorded history of over 3,400 years.', sp: 'Es una de las ciudades más antiguas del mundo, con una historia registrada de más de 3.400 años.', pt: 'É uma das cidades mais antigas do mundo, com uma história registrada de mais de 3.400 anos.' } },
    { id: 187, label: 'Santorini', tz: 'Europe/Athens', funFact: { en: 'The island is the site of one of the largest volcanic eruptions in history.', sp: 'La isla es el lugar de una de las mayores erupciones volcánicas de la historia.', pt: 'A ilha é o local de uma das maiores erupções vulcânicas da história.' } },
    { id: 143, label: 'Greece', tz: 'Europe/Athens', funFact: { en: 'The Olympic Games originated in ancient Greece.', sp: 'Los Juegos Olímpicos se originaron en la antigua Grecia.', pt: 'Os Jogos Olímpicos originaram-se na Grécia Antiga.' } },
    // Ukraine
    { id: 33, label: 'Kyiv', tz: 'Europe/Kyiv', funFact: { en: 'Arsenalna is the deepest metro station in the world (105.5 meters).', sp: 'Arsenalna es la estación de metro más profunda del mundo (105,5 metros).', pt: 'Arsenalna é a estação de metrô mais profunda do mundo (105,5 metros).' } },
    { id: 144, label: 'Ukraine', tz: 'Europe/Kyiv', funFact: { en: 'It is the largest country entirely within Europe.', sp: 'Es el país más grande que se encuentra completamente dentro de Europa.', pt: 'É o maior país inteiramente dentro da Europa.' } },
    // Russia
    { id: 34, label: 'Moscow', tz: 'Europe/Moscow', funFact: { en: 'The Moscow Metro is one of the most beautiful and ornate in the world.', sp: 'El Metro de Moscú es uno de los más bellos y ornamentados del mundo.', pt: 'O Metrô de Moscou é um dos mais belos e ornamentados do mundo.' } },
    { id: 87, label: 'Saint Petersburg', tz: 'Europe/Moscow', funFact: { en: 'It has the northernmost metro system in the world.', sp: 'Tiene el sistema de metro más septentrional del mundo.', pt: 'Possui o sistema de metrô mais ao norte do mundo.' } },
    // Turkey
    { id: 35, label: 'Istanbul', tz: 'Europe/Istanbul', funFact: { en: 'It is the only city in the world that straddles two continents: Europe and Asia.', sp: 'Es la única ciudad del mundo que se extiende por dos continentes: Europa y Asia.', pt: 'É a única cidade do mundo que abrange dois continentes: Europa e Ásia.' } },
    { id: 188, label: 'Cappadocia', tz: 'Europe/Istanbul', funFact: { en: 'It is famous for its unique "fairy chimneys" and hot air balloon rides.', sp: 'Es famosa por sus singulares "chimeneas de hadas" y sus paseos en globo aerostático.', pt: 'É famosa por suas "chaminés de fada" únicas e passeios de balão de ar quente.' } },
    { id: 145, label: 'Turkey', tz: 'Europe/Istanbul', funFact: { en: 'Santa Claus (Saint Nicholas) was born in Patara, Turkey.', sp: 'Papá Noel (San Nicolás) nació en Patara, Turquía.', pt: 'Papai Noel (São Nicolau) nasceu em Patara, na Turquia.' } },
    // Portugal
    { id: 88, label: 'Lisbon', tz: 'Europe/Lisbon', funFact: { en: 'It is the second-oldest European capital city after Athens.', sp: 'Es la segunda capital europea más antigua, después de Atenas.', pt: 'É a segunda capital europeia mais antiga, depois de Atenas.' } },
    { id: 189, label: 'Porto', tz: 'Europe/Lisbon', funFact: { en: 'The city is famous for its Port wine.', sp: 'La ciudad es famosa por su vino de Oporto.', pt: 'A cidade é famosa pelo seu vinho do Porto.' } },
    { id: 146, label: 'Portugal', tz: 'Europe/Lisbon', funFact: { en: 'It has the oldest bookstore in the world, Bertrand Bookstore (1732).', sp: 'Tiene la librería más antigua del mundo, la Librería Bertrand (1732).', pt: 'Possui a livraria mais antiga do mundo, a Livraria Bertrand (1732).' } },
    // Czech Republic
    { id: 89, label: 'Prague', tz: 'Europe/Prague', funFact: { en: 'Prague Castle is the largest ancient castle in the world.', sp: 'El Castillo de Praga es el castillo antiguo más grande del mundo.', pt: 'O Castelo de Praga é o maior castelo antigo do mundo.' } },
    { id: 147, label: 'Czech Republic', tz: 'Europe/Prague', funFact: { en: 'It has the highest beer consumption per capita in the world.', sp: 'Tiene el mayor consumo de cerveza per cápita del mundo.', pt: 'Possui o maior consumo de cerveja per capita do mundo.' } },
    // Austria
    { id: 90, label: 'Vienna', tz: 'Europe/Vienna', funFact: { en: 'It is known as the "City of Music" and was home to Mozart and Beethoven.', sp: 'Es conocida como la "Ciudad de la Música" y fue el hogar de Mozart y Beethoven.', pt: 'É conhecida como a "Cidade da Música" e foi o lar de Mozart e Beethoven.' } },
    { id: 148, label: 'Austria', tz: 'Europe/Vienna', funFact: { en: 'The sewing machine was invented in Austria.', sp: 'La máquina de coser fue inventada en Austria.', pt: 'A máquina de costura foi inventada na Áustria.' } },
    // Switzerland
    { id: 91, label: 'Zurich', tz: 'Europe/Zurich', funFact: { en: 'It is often ranked as one of the cities with the highest quality of life in the world.', sp: 'A menudo se clasifica como una de las ciudades con la mejor calidad de vida del mundo.', pt: 'É frequentemente classificada como uma das cidades com a maior qualidade de vida do mundo.' } },
    { id: 190, label: 'Geneva', tz: 'Europe/Zurich', funFact: { en: 'The World Wide Web was invented at CERN in Geneva.', sp: 'La World Wide Web fue inventada en el CERN de Ginebra.', pt: 'A World Wide Web foi inventada no CERN em Genebra.' } },
    { id: 149, label: 'Switzerland', tz: 'Europe/Zurich', funFact: { en: 'It has more high peaks than any other country in Europe.', sp: 'Tiene más picos altos que cualquier otro país de Europa.', pt: 'Possui mais picos altos do que qualquer outro país da Europa.' } },
    // Belgium
    { id: 92, label: 'Brussels', tz: 'Europe/Brussels', funFact: { en: 'The comic strip "The Smurfs" was created in Brussels.', sp: 'La tira cómica "Los Pitufos" fue creada en Bruselas.', pt: 'A história em quadrinhos "Os Smurfs" foi criada em Bruxelas.' } },
    { id: 150, label: 'Belgium', tz: 'Europe/Brussels', funFact: { en: 'It produces over 220,000 tons of chocolate per year.', sp: 'Produce más de 220.000 toneladas de chocolate al año.', pt: 'Produz mais de 220.000 toneladas de chocolate por ano.' } },
    // Denmark
    { id: 93, label: 'Copenhagen', tz: 'Europe/Copenhagen', funFact: { en: 'Tivoli Gardens, one of the world\'s oldest amusement parks, is located here.', sp: 'Los Jardines de Tívoli, uno de los parques de atracciones más antiguos del mundo, se encuentra aquí.', pt: 'Os Jardins do Tivoli, um dos parques de diversões mais antigos do mundo, está localizado aqui.' } },
    { id: 151, label: 'Denmark', tz: 'Europe/Copenhagen', funFact: { en: 'The Danish flag is the oldest continuously used national flag in the world.', sp: 'La bandera danesa es la bandera nacional de uso continuo más antigua del mundo.', pt: 'A bandeira dinamarquesa é a bandeira nacional mais antiga do mundo em uso contínuo.' } },
    // Poland
    { id: 94, label: 'Warsaw', tz: 'Europe/Warsaw', funFact: { en: 'Over 85% of the city was destroyed during World War II and has since been rebuilt.', sp: 'Más del 85% de la ciudad fue destruida durante la Segunda Guerra Mundial y ha sido reconstruida desde entonces.', pt: 'Mais de 85% da cidade foi destruída durante a Segunda Guerra Mundial e desde então foi reconstruída.' } },
    { id: 210, label: 'Krakow', tz: 'Europe/Warsaw', funFact: { en: 'The historic centre of Krakow was one of the first sites chosen for the original UNESCO World Heritage List.', sp: 'El centro histórico de Cracovia fue uno de los primeros sitios elegidos para la Lista del Patrimonio Mundial original de la UNESCO.', pt: 'O centro histórico de Cracóvia foi um dos primeiros locais escolhidos para a Lista do Patrimônio Mundial original da UNESCO.' } },
    { id: 152, label: 'Poland', tz: 'Europe/Warsaw', funFact: { en: 'It has the world\'s largest brick castle, Malbork Castle.', sp: 'Tiene el castillo de ladrillos más grande del mundo, el Castillo de Malbork.', pt: 'Possui o maior castelo de tijolos do mundo, o Castelo de Malbork.' } },
    // Hungary
    { id: 208, label: 'Budapest', tz: 'Europe/Budapest', funFact: { en: 'It has the highest number of thermal springs within a capital city in the world.', sp: 'Tiene el mayor número de fuentes termales dentro de una capital en el mundo.', pt: 'Possui o maior número de fontes termais dentro de uma capital no mundo.' } },
    // Iceland
    { id: 213, label: 'Reykjavik', tz: 'Atlantic/Reykjavik', funFact: { en: 'It is the world\'s northernmost capital of a sovereign state.', sp: 'Es la capital más septentrional del mundo de un estado soberano.', pt: 'É a capital mais setentrional do mundo de um estado soberano.' } },
    // Croatia
    { id: 214, label: 'Dubrovnik', tz: 'Europe/Zagreb', funFact: { en: 'It was a major filming location for "King\'s Landing" in Game of Thrones.', sp: 'Fue un lugar de rodaje importante para "Desembarco del Rey" en Juego de Tronos.', pt: 'Foi um importante local de filmagem para "Porto Real" em Game of Thrones.' } },

    // --- Asia ---
    // Japan
    { id: 36, label: 'Tokyo', tz: 'Asia/Tokyo', funFact: { en: 'It is the most populous metropolitan area in the world.', sp: 'Es el área metropolitana más poblada del mundo.', pt: 'É a área metropolitana mais populosa do mundo.' } },
    { id: 191, label: 'Kyoto', tz: 'Asia/Tokyo', funFact: { en: 'It was the imperial capital of Japan for more than one thousand years.', sp: 'Fue la capital imperial de Japón durante más de mil años.', pt: 'Foi a capital imperial do Japão por mais de mil anos.' } },
    { id: 192, label: 'Mount Fuji', tz: 'Asia/Tokyo', funFact: { en: 'It is an active volcano that last erupted in 1707.', sp: 'Es un volcán activo que entró en erupción por última vez en 1707.', pt: 'É um vulcão ativo que entrou em erupção pela última vez em 1707.' } },
    { id: 153, label: 'Japan', tz: 'Asia/Tokyo', funFact: { en: 'It has the world\'s oldest continuously operating company, a construction firm founded in 578 AD.', sp: 'Tiene la empresa en funcionamiento continuo más antigua del mundo, una empresa de construcción fundada en el 578 d.C.', pt: 'Possui a empresa em operação contínua mais antiga do mundo, uma empresa de construção fundada em 578 d.C.' } },
    // South Korea
    { id: 37, label: 'Seoul', tz: 'Asia/Seoul', funFact: { en: 'The city\'s official name is "Seoul Special City".', sp: 'El nombre oficial de la ciudad es "Ciudad Especial de Seúl".', pt: 'O nome oficial da cidade é "Cidade Especial de Seul".' } },
    { id: 154, label: 'South Korea', tz: 'Asia/Seoul', funFact: { en: 'The country has the fastest average internet speed in the world.', sp: 'El país tiene la velocidad de internet promedio más rápida del mundo.', pt: 'O país tem a velocidade média de internet mais rápida do mundo.' } },
    // China
    { id: 38, label: 'Beijing', tz: 'Asia/Shanghai', funFact: { en: 'It is the first city to have hosted both the Summer and Winter Olympic Games.', sp: 'Es la primera ciudad que ha sido sede de los Juegos Olímpicos de Verano e Invierno.', pt: 'É a primeira cidade a ter sediado os Jogos Olímpicos de Verão e de Inverno.' } },
    { id: 39, label: 'Shanghai', tz: 'Asia/Shanghai', funFact: { en: 'It has the world\'s fastest commercial train, the Shanghai Maglev.', sp: 'Tiene el tren comercial más rápido del mundo, el Shanghai Maglev.', pt: 'Possui o trem comercial mais rápido do mundo, o Shanghai Maglev.' } },
    { id: 193, label: 'Great Wall of China', tz: 'Asia/Shanghai', funFact: { en: 'It is not a single continuous wall but a system of walls, watchtowers, and fortresses.', sp: 'No es una única muralla continua, sino un sistema de muros, atalayas y fortalezas.', pt: 'Não é uma única muralha contínua, mas um sistema de muralhas, torres de vigia e fortalezas.' } },
    { id: 40, label: 'Hong Kong', tz: 'Asia/Hong_Kong', funFact: { en: 'It has more skyscrapers than any other city in the world.', sp: 'Tiene más rascacielos que cualquier otra ciudad del mundo.', pt: 'Possui mais arranha-céus do que qualquer outra cidade do mundo.' } },
    // Singapore
    { id: 41, label: 'Singapore', tz: 'Asia/Singapore', funFact: { en: 'It is one of only three city-states in the world (the others are Monaco and Vatican City).', sp: 'Es una de las tres únicas ciudades-estado del mundo (las otras son Mónaco y Ciudad del Vaticano).', pt: 'É uma das três únicas cidades-estado do mundo (as outras são Mônaco e Cidade do Vaticano).' } },
    // Thailand
    { id: 42, label: 'Bangkok', tz: 'Asia/Bangkok', funFact: { en: 'Its full ceremonial name is one of the longest city names in the world.', sp: 'Su nombre ceremonial completo es uno de los nombres de ciudad más largos del mundo.', pt: 'Seu nome cerimonial completo é um dos nomes de cidade mais longos do mundo.' } },
    { id: 194, label: 'Phuket', tz: 'Asia/Bangkok', funFact: { en: 'It is Thailand\'s largest island.', sp: 'Es la isla más grande de Tailandia.', pt: 'É a maior ilha da Tailândia.' } },
    { id: 211, label: 'Chiang Mai', tz: 'Asia/Bangkok', funFact: { en: 'It has over 300 Buddhist temples.', sp: 'Tiene más de 300 templos budistas.', pt: 'Possui mais de 300 templos budistas.' } },
    { id: 155, label: 'Thailand', tz: 'Asia/Bangkok', funFact: { en: 'It is the only country in Southeast Asia that was never colonized by a European power.', sp: 'Es el único país del sudeste asiático que nunca fue colonizado por una potencia europea.', pt: 'É o único país do Sudeste Asiático que nunca foi colonizado por uma potência europeia.' } },
    // United Arab Emirates
    { id: 43, label: 'Dubai', tz: 'Asia/Dubai', funFact: { en: 'The Burj Khalifa is the tallest building in the world.', sp: 'El Burj Khalifa es el edificio más alto del mundo.', pt: 'O Burj Khalifa é o edifício mais alto do mundo.' } },
    { id: 95, label: 'Abu Dhabi', tz: 'Asia/Dubai', funFact: { en: 'It is one of the richest cities in the world due to its oil reserves.', sp: 'Es una de las ciudades más ricas del mundo debido a sus reservas de petróleo.', pt: 'É uma das cidades mais ricas do mundo devido às suas reservas de petróleo.' } },
    { id: 156, label: 'United Arab Emirates', tz: 'Asia/Dubai', funFact: { en: 'The country has a Minister for Happiness.', sp: 'El país tiene un Ministro de la Felicidad.', pt: 'O país tem um Ministro da Felicidade.' } },
    // India
    { id: 44, label: 'Mumbai', tz: 'Asia/Kolkata', funFact: { en: 'It is the heart of India\'s "Bollywood" film industry.', sp: 'Es el corazón de la industria cinematográfica "Bollywood" de la India.', pt: 'É o coração da indústria cinematográfica "Bollywood" da Índia.' } },
    { id: 45, label: 'New Delhi', tz: 'Asia/Kolkata', funFact: { en: 'It is one of the greenest capital cities in the world.', sp: 'Es una de las capitales más verdes del mundo.', pt: 'É uma das capitais mais verdes do mundo.' } },
    { id: 96, label: 'Bangalore', tz: 'Asia/Kolkata', funFact: { en: 'It is known as the "Silicon Valley of India".', sp: 'Es conocido como el "Silicon Valley de la India".', pt: 'É conhecido como o "Vale do Silício da Índia".' } },
    { id: 195, label: 'Agra', tz: 'Asia/Kolkata', funFact: { en: 'It is home to the Taj Mahal, one of the New Seven Wonders of the World.', sp: 'Alberga el Taj Mahal, una de las Nuevas Siete Maravillas del Mundo.', pt: 'É o lar do Taj Mahal, uma das Novas Sete Maravilhas do Mundo.' } },
    // Israel
    { id: 46, label: 'Jerusalem', tz: 'Asia/Jerusalem', funFact: { en: 'It is a holy city to three major Abrahamic religions: Judaism, Christianity, and Islam.', sp: 'Es una ciudad santa para tres grandes religiones abrahámicas: el judaísmo, el cristianismo y el islam.', pt: 'É uma cidade sagrada para três grandes religiões abraâmicas: judaísmo, cristianismo e islamismo.' } },
    { id: 157, label: 'Israel', tz: 'Asia/Jerusalem', funFact: { en: 'It has the highest number of museums per capita in the world.', sp: 'Tiene el mayor número de museos per cápita del mundo.', pt: 'Possui o maior número de museus per capita do mundo.' } },
    // Indonesia
    { id: 47, label: 'Jakarta', tz: 'Asia/Jakarta', funFact: { en: 'It is the most populous city in Southeast Asia.', sp: 'Es la ciudad más poblada del sudeste asiático.', pt: 'É a cidade mais populosa do Sudeste Asiático.' } },
    { id: 196, label: 'Bali', tz: 'Asia/Makassar', funFact: { en: 'It is known as the "Island of the Gods" for its thousands of Hindu temples.', sp: 'Es conocida como la "Isla de los Dioses" por sus miles de templos hindúes.', pt: 'É conhecida como a "Ilha dos Deuses" por seus milhares de templos hindus.' } },
    // Philippines
    { id: 48, label: 'Manila', tz: 'Asia/Manila', funFact: { en: 'It is the most densely populated city proper in the world.', sp: 'Es la ciudad propiamente dicha más densamente poblada del mundo.', pt: 'É a cidade propriamente dita mais densamente povoada do mundo.' } },
    { id: 158, label: 'Philippines', tz: 'Asia/Manila', funFact: { en: 'It is composed of 7,641 islands.', sp: 'Se compone de 7.641 islas.', pt: 'É composto por 7.641 ilhas.' } },
    // Taiwan
    { id: 97, label: 'Taipei', tz: 'Asia/Taipei', funFact: { en: 'The Taipei 101 was the world\'s tallest building from 2004 to 2010.', sp: 'El Taipei 101 fue el edificio más alto del mundo de 2004 a 2010.', pt: 'O Taipei 101 foi o edifício mais alto do mundo de 2004 a 2010.' } },
    { id: 159, label: 'Taiwan', tz: 'Asia/Taipei', funFact: { en: 'It is the world\'s largest producer of orchids.', sp: 'Es el mayor productor de orquídeas del mundo.', pt: 'É o maior produtor de orquídeas do mundo.' } },
    // Malaysia
    { id: 98, label: 'Kuala Lumpur', tz: 'Asia/Kuala_Lumpur', funFact: { en: 'The Petronas Towers were the tallest buildings in the world from 1998 to 2004.', sp: 'Las Torres Petronas fueron los edificios más altos del mundo de 1998 a 2004.', pt: 'As Torres Petronas foram os edifícios mais altos do mundo de 1998 a 2004.' } },
    { id: 160, label: 'Malaysia', tz: 'Asia/Kuala_Lumpur', funFact: { en: 'It is home to the world\'s largest cave chamber, the Sarawak Chamber.', sp: 'Alberga la cámara de cueva más grande del mundo, la Cámara de Sarawak.', pt: 'É o lar da maior câmara de caverna do mundo, a Câmara de Sarawak.' } },
    // Vietnam
    { id: 99, label: 'Ho Chi Minh City', tz: 'Asia/Ho_Chi_Minh', funFact: { en: 'It was formerly known as Saigon.', sp: 'Anteriormente se conocía como Saigón.', pt: 'Era anteriormente conhecida como Saigon.' } },
    { id: 197, label: 'Ha Long Bay', tz: 'Asia/Ho_Chi_Minh', funFact: { en: 'It means "Descending Dragon" and features thousands of limestone karsts.', sp: 'Significa "Dragón Descendente" y cuenta con miles de karsts de piedra caliza.', pt: 'Significa "Dragão Descendente" e apresenta milhares de carstes de calcário.' } },
    { id: 212, label: 'Da Nang', tz: 'Asia/Ho_Chi_Minh', funFact: { en: 'It is famous for its Dragon Bridge, which breathes fire on weekends.', sp: 'Es famosa por su Puente del Dragón, que escupe fuego los fines de semana.', pt: 'É famosa pela sua Ponte do Dragão, que cospe fogo nos fins de semana.' } },
    { id: 161, label: 'Vietnam', tz: 'Asia/Ho_Chi_Minh', funFact: { en: 'It is the world\'s largest exporter of cashews.', sp: 'Es el mayor exportador de anacardos del mundo.', pt: 'É o maior exportador de castanha de caju do mundo.' } },
    // Saudi Arabia
    { id: 100, label: 'Riyadh', tz: 'Asia/Riyadh', funFact: { en: 'Its name is derived from the Arabic word "rawdah," meaning "gardens" or "meadows".', sp: 'Su nombre deriva de la palabra árabe "rawdah", que significa "jardines" o "prados".', pt: 'Seu nome deriva da palavra árabe "rawdah", que significa "jardins" ou "prados".' } },
    { id: 162, label: 'Saudi Arabia', tz: 'Asia/Riyadh', funFact: { en: 'It is the largest country in the world without a river.', sp: 'Es el país más grande del mundo sin un río.', pt: 'É o maior país do mundo sem um rio.' } },
    // Qatar
    { id: 101, label: 'Doha', tz: 'Asia/Qatar', funFact: { en: 'It hosted the first-ever FIFA World Cup in the Middle East in 2022.', sp: 'Fue sede de la primera Copa Mundial de la FIFA en Oriente Medio en 2022.', pt: 'Sediou a primeira Copa do Mundo da FIFA no Oriente Médio em 2022.' } },
    { id: 163, label: 'Qatar', tz: 'Asia/Qatar', funFact: { en: 'It is the richest country in the world by GDP per capita.', sp: 'Es el país más rico del mundo por PIB per cápita.', pt: 'É o país mais rico do mundo em PIB per capita.' } },
    // Cambodia
    { id: 215, label: 'Siem Reap', tz: 'Asia/Phnom_Penh', funFact: { en: 'It is the gateway to the ancient ruins of Angkor Wat.', sp: 'Es la puerta de entrada a las antiguas ruinas de Angkor Wat.', pt: 'É a porta de entrada para as antigas ruínas de Angkor Wat.' } },
    // Nepal
    { id: 216, label: 'Kathmandu', tz: 'Asia/Kathmandu', funFact: { en: 'It is home to the only living goddess in the world, the Kumari.', sp: 'Alberga a la única diosa viviente del mundo, la Kumari.', pt: 'É o lar da única deusa viva do mundo, a Kumari.' } },
    // Jordan
    { id: 217, label: 'Petra', tz: 'Asia/Amman', funFact: { en: 'Known as the "Rose City" because of the color of the rock from which it is carved.', sp: 'Conocida como la "Ciudad Rosa" por el color de la roca en la que está tallada.', pt: 'Conhecida como a "Cidade Rosa" pela cor da rocha da qual é esculpida.' } },

    // --- Africa ---
    // Egypt
    { id: 49, label: 'Cairo', tz: 'Africa/Cairo', funFact: { en: 'It is home to the only remaining ancient wonder of the world, the Great Pyramid of Giza.', sp: 'Alberga la única maravilla antigua del mundo que queda, la Gran Pirámide de Giza.', pt: 'É o lar da única maravilha antiga remanescente do mundo, a Grande Pirâmide de Gizé.' } },
    { id: 198, label: 'Giza', tz: 'Africa/Cairo', funFact: { en: 'The Great Sphinx is the oldest known monumental sculpture in Egypt.', sp: 'La Gran Esfinge es la escultura monumental más antigua conocida de Egipto.', pt: 'A Grande Esfinge é a mais antiga escultura monumental conhecida no Egito.' } },
    { id: 199, label: 'Luxor', tz: 'Africa/Cairo', funFact: { en: 'It is often called the world\'s greatest open-air museum.', sp: 'A menudo se le llama el museo al aire libre más grande del mundo.', pt: 'É frequentemente chamado de o maior museu a céu aberto do mundo.' } },
    { id: 164, label: 'Egypt', tz: 'Africa/Cairo', funFact: { en: 'The ancient Egyptians invented the 365-day calendar.', sp: 'Los antiguos egipcios inventaron el calendario de 365 días.', pt: 'Os antigos egípcios inventaram o calendário de 365 dias.' } },
    // South Africa
    { id: 50, label: 'Johannesburg', tz: 'Africa/Johannesburg', funFact: { en: 'It is the world\'s largest city not situated on a river, lake, or coastline.', sp: 'Es la ciudad más grande del mundo que no está situada en un río, lago o costa.', pt: 'É a maior cidade do mundo não situada em um rio, lago ou litoral.' } },
    { id: 102, label: 'Cape Town', tz: 'Africa/Johannesburg', funFact: { en: 'It is home to the most diverse floral kingdom in the world.', sp: 'Alberga el reino floral más diverso del mundo.', pt: 'É o lar do reino floral mais diversificado do mundo.' } },
    { id: 200, label: 'Kruger National Park', tz: 'Africa/Johannesburg', funFact: { en: 'It is one of the largest game reserves in Africa.', sp: 'Es una de las reservas de caza más grandes de África.', pt: 'É uma das maiores reservas de caça da África.' } },
    { id: 165, label: 'South Africa', tz: 'Africa/Johannesburg', funFact: { en: 'It has three capital cities: Pretoria, Cape Town, and Bloemfontein.', sp: 'Tiene tres capitales: Pretoria, Ciudad del Cabo y Bloemfontein.', pt: 'Possui três capitais: Pretória, Cidade do Cabo e Bloemfontein.' } },
    // Kenya
    { id: 51, label: 'Nairobi', tz: 'Africa/Nairobi', funFact: { en: 'Nairobi National Park is the only national park within a capital city.', sp: 'El Parque Nacional de Nairobi es el único parque nacional dentro de una capital.', pt: 'O Parque Nacional de Nairobi é o único parque nacional dentro de uma capital.' } },
    { id: 166, label: 'Kenya', tz: 'Africa/Nairobi', funFact: { en: 'The Great Rift Valley, a massive geological feature, runs through Kenya.', sp: 'El Gran Valle del Rift, una enorme característica geológica, atraviesa Kenia.', pt: 'O Grande Vale do Rift, uma enorme característica geológica, atravessa o Quênia.' } },
    // Nigeria
    { id: 52, label: 'Lagos', tz: 'Africa/Lagos', funFact: { en: 'It has the busiest seaport in Africa.', sp: 'Tiene el puerto marítimo más concurrido de África.', pt: 'Possui o porto marítimo mais movimentado da África.' } },
    { id: 167, label: 'Nigeria', tz: 'Africa/Lagos', funFact: { en: 'It is the most populous country in Africa.', sp: 'Es el país más poblado de África.', pt: 'É o país mais populoso da África.' } },
    // Morocco
    { id: 53, label: 'Casablanca', tz: 'Africa/Casablanca', funFact: { en: 'It is home to the largest mosque in Africa, the Hassan II Mosque.', sp: 'Alberga la mezquita más grande de África, la Mezquita Hassan II.', pt: 'É o lar da maior mesquita da África, a Mesquita Hassan II.' } },
    { id: 201, label: 'Marrakech', tz: 'Africa/Casablanca', funFact: { en: 'Its main square, Djemaa el-Fna, is a UNESCO Masterpiece of the Oral and Intangible Heritage of Humanity.', sp: 'Su plaza principal, Djemaa el-Fna, es una Obra Maestra del Patrimonio Oral e Inmaterial de la Humanidad por la UNESCO.', pt: 'Sua praça principal, Djemaa el-Fna, é uma Obra-Prima do Patrimônio Oral e Imaterial da Humanidade da UNESCO.' } },
    { id: 168, label: 'Morocco', tz: 'Africa/Casablanca', funFact: { en: 'It is home to the world\'s oldest university, the University of Al-Karaouine.', sp: 'Alberga la universidad más antigua del mundo, la Universidad de Al-Karaouine.', pt: 'É o lar da universidade mais antiga do mundo, a Universidade de Al-Karaouine.' } },
    // Ghana
    { id: 103, label: 'Accra', tz: 'Africa/Accra', funFact: { en: 'It is a major center for Afrobeats music.', sp: 'Es un importante centro de la música Afrobeats.', pt: 'É um grande centro da música Afrobeats.' } },
    { id: 169, label: 'Ghana', tz: 'Africa/Accra', funFact: { en: 'It was the first country in sub-Saharan Africa to gain independence.', sp: 'Fue el primer país del África subsahariana en obtener la independencia.', pt: 'Foi o primeiro país da África subsaariana a obter a independência.' } },
    // Algeria
    { id: 104, label: 'Algiers', tz: 'Africa/Algiers', funFact: { en: 'Its Casbah is a UNESCO World Heritage site.', sp: 'Su Casbah es Patrimonio de la Humanidad por la UNESCO.', pt: 'Sua Casbah é um Patrimônio Mundial da UNESCO.' } },
    { id: 170, label: 'Algeria', tz: 'Africa/Algiers', funFact: { en: 'It is the largest country in Africa by land area.', sp: 'Es el país más grande de África por superficie terrestre.', pt: 'É o maior país da África em área terrestre.' } },
    // Tanzania
    { id: 218, label: 'Zanzibar', tz: 'Africa/Dar_es_Salaam', funFact: { en: 'Freddie Mercury, lead singer of Queen, was born in Zanzibar.', sp: 'Freddie Mercury, vocalista de Queen, nació en Zanzíbar.', pt: 'Freddie Mercury, vocalista do Queen, nasceu em Zanzibar.' } },
    // Zambia / Zimbabwe
    { id: 219, label: 'Victoria Falls', tz: 'Africa/Lusaka', funFact: { en: 'It is the largest waterfall in the world by combined width and height.', sp: 'Es la cascada más grande del mundo por su anchura y altura combinadas.', pt: 'É a maior cachoeira do mundo em largura e altura combinadas.' } },

    // --- Oceania ---
    // Australia
    { id: 54, label: 'Sydney', tz: 'Australia/Sydney', funFact: { en: 'The Sydney Opera House\'s design was inspired by peeling an orange.', sp: 'El diseño de la Ópera de Sídney se inspiró en pelar una naranja.', pt: 'O design da Ópera de Sydney foi inspirado em descascar uma laranja.' } },
    { id: 55, label: 'Melbourne', tz: 'Australia/Melbourne', funFact: { en: 'It is often called the "Sporting Capital of the World".', sp: 'A menudo se le llama la "Capital Deportiva del Mundo".', pt: 'É frequentemente chamada de "Capital Esportiva do Mundo".' } },
    { id: 56, label: 'Brisbane', tz: 'Australia/Brisbane', funFact: { en: 'It is the third-most populous city in Australia.', sp: 'Es la tercera ciudad más poblada de Australia.', pt: 'É a terceira cidade mais populosa da Austrália.' } },
    { id: 57, label: 'Perth', tz: 'Australia/Perth', funFact: { en: 'It is one of the most isolated major cities in the world.', sp: 'Es una de las principales ciudades más aisladas del mundo.', pt: 'É uma das principais cidades mais isoladas do mundo.' } },
    { id: 58, label: 'Adelaide', tz: 'Australia/Adelaide', funFact: { en: 'It is known as the "20-Minute City" because it\'s easy to get around.', sp: 'Es conocida como la "Ciudad de los 20 Minutos" porque es fácil moverse por ella.', pt: 'É conhecida como a "Cidade dos 20 Minutos" porque é fácil de se locomover.' } },
    { id: 59, label: 'Darwin', tz: 'Australia/Darwin', funFact: { en: 'It has been almost completely rebuilt twice, once after a WWII air raid and once after a cyclone.', sp: 'Ha sido reconstruida casi por completo dos veces, una después de un ataque aéreo de la Segunda Guerra Mundial y otra después de un ciclón.', pt: 'Foi quase completamente reconstruída duas vezes, uma após um ataque aéreo da Segunda Guerra Mundial e outra após um ciclone.' } },
    { id: 105, label: 'Canberra', tz: 'Australia/Sydney', funFact: { en: 'It is a planned city, designed by American architect Walter Burley Griffin.', sp: 'Es una ciudad planificada, diseñada por el arquitecto estadounidense Walter Burley Griffin.', pt: 'É uma cidade planejada, projetada pelo arquiteto americano Walter Burley Griffin.' } },
    { id: 202, label: 'Uluru', tz: 'Australia/Darwin', funFact: { en: 'It is a massive sandstone monolith that is sacred to Indigenous Australians.', sp: 'Es un enorme monolito de arenisca sagrado para los australianos indígenas.', pt: 'É um enorme monólito de arenito sagrado para os australianos indígenas.' } },
    { id: 203, label: 'Great Barrier Reef', tz: 'Australia/Brisbane', funFact: { en: 'It is the world\'s largest coral reef system and can be seen from outer space.', sp: 'Es el sistema de arrecifes de coral más grande del mundo y se puede ver desde el espacio exterior.', pt: 'É o maior sistema de recifes de coral do mundo e pode ser visto do espaço sideral.' } },
    // Australian States
    { id: 119, label: 'New South Wales', tz: 'Australia/Sydney', funFact: { en: 'It is Australia\'s most populous state.', sp: 'Es el estado más poblado de Australia.', pt: 'É o estado mais populoso da Austrália.' } },
    { id: 120, label: 'Victoria', tz: 'Australia/Melbourne', funFact: { en: 'It is the most densely populated state in Australia.', sp: 'Es el estado más densamente poblado de Australia.', pt: 'É o estado mais densamente povoado da Austrália.' } },
    { id: 121, label: 'Queensland', tz: 'Australia/Brisbane', funFact: { en: 'It is known as the "Sunshine State" for its tropical and sub-tropical climates.', sp: 'Es conocido como el "Estado del Sol" por sus climas tropicales y subtropicales.', pt: 'É conhecido como o "Estado do Sol" por seus climas tropicais e subtropicais.' } },
    { id: 122, label: 'Western Australia', tz: 'Australia/Perth', funFact: { en: 'It is the largest state in Australia by area.', sp: 'Es el estado más grande de Australia por superficie.', pt: 'É o maior estado da Austrália em área.' } },
    // New Zealand
    { id: 60, label: 'Auckland', tz: 'Pacific/Auckland', funFact: { en: 'It is the largest Polynesian city in the world.', sp: 'Es la ciudad polinesia más grande del mundo.', pt: 'É a maior cidade polinésia do mundo.' } },
    { id: 106, label: 'Wellington', tz: 'Pacific/Auckland', funFact: { en: 'It is the southernmost capital city in the world.', sp: 'Es la capital más meridional del mundo.', pt: 'É a capital mais ao sul do mundo.' } },
    { id: 204, label: 'Queenstown', tz: 'Pacific/Auckland', funFact: { en: 'It is known as the "Adventure Capital of the World".', sp: 'Es conocida como la "Capital Mundial de la Aventura".', pt: 'É conhecida como a "Capital Mundial da Aventura".' } },
    { id: 171, label: 'New Zealand', tz: 'Pacific/Auckland', funFact: { en: 'It was the first country in the world to grant women the right to vote.', sp: 'Fue el primer país del mundo en conceder el derecho al voto a las mujeres.', pt: 'Foi o primeiro país do mundo a conceder o direito de voto às mulheres.' } },
    // Fiji
    { id: 61, label: 'Fiji', tz: 'Pacific/Fiji', funFact: { en: 'It is an archipelago of more than 330 islands.', sp: 'Es un archipiélago de más de 330 islas.', pt: 'É um arquipélago de mais de 330 ilhas.' } },
];