export type TimezoneOption = {
    id: number;
    label: string;
    tz: string;
};

export const timezones: TimezoneOption[] = [
    // --- North America ---
    // United States
    { id: 1, label: 'New York', tz: 'America/New_York' },
    { id: 2, label: 'Chicago', tz: 'America/Chicago' },
    { id: 3, label: 'Denver', tz: 'America/Denver' },
    { id: 4, label: 'Los Angeles', tz: 'America/Los_Angeles' },
    { id: 5, label: 'Anchorage', tz: 'America/Anchorage' },
    { id: 6, label: 'Honolulu', tz: 'Pacific/Honolulu' },
    { id: 7, label: 'Phoenix', tz: 'America/Phoenix' },
    { id: 62, label: 'Atlanta', tz: 'America/New_York' },
    { id: 63, label: 'Boston', tz: 'America/New_York' },
    { id: 64, label: 'Miami', tz: 'America/New_York' },
    { id: 65, label: 'Washington D.C.', tz: 'America/New_York' },
    { id: 66, label: 'Dallas', tz: 'America/Chicago' },
    { id: 67, label: 'Houston', tz: 'America/Chicago' },
    { id: 68, label: 'New Orleans', tz: 'America/Chicago' },
    { id: 69, label: 'Salt Lake City', tz: 'America/Denver' },
    { id: 70, label: 'San Francisco', tz: 'America/Los_Angeles' },
    { id: 71, label: 'Seattle', tz: 'America/Los_Angeles' },
    { id: 72, label: 'Las Vegas', tz: 'America/Los_Angeles' },
    // US States & Regions
    { id: 107, label: 'California', tz: 'America/Los_Angeles' },
    { id: 108, label: 'Texas', tz: 'America/Chicago' },
    { id: 109, label: 'Florida', tz: 'America/New_York' },
    { id: 110, label: 'Arizona', tz: 'America/Phoenix' },
    { id: 111, label: 'Colorado', tz: 'America/Denver' },
    { id: 112, label: 'Illinois', tz: 'America/Chicago' },

    // Canada
    { id: 8, label: 'Toronto', tz: 'America/Toronto' },
    { id: 9, label: 'Vancouver', tz: 'America/Vancouver' },
    { id: 10, label: 'Halifax', tz: 'America/Halifax' },
    { id: 11, label: 'Winnipeg', tz: 'America/Winnipeg' },
    { id: 73, label: 'Montreal', tz: 'America/Toronto' },
    { id: 74, label: 'Ottawa', tz: 'America/Toronto' },
    { id: 75, label: 'Calgary', tz: 'America/Edmonton' },
    { id: 76, label: 'Edmonton', tz: 'America/Edmonton' },
    // Canadian Provinces
    { id: 113, label: 'Ontario', tz: 'America/Toronto' },
    { id: 114, label: 'Quebec', tz: 'America/Toronto' },
    { id: 115, label: 'British Columbia', tz: 'America/Vancouver' },
    { id: 116, label: 'Alberta', tz: 'America/Edmonton' },

    // Mexico
    { id: 12, label: 'Mexico City', tz: 'America/Mexico_City' },
    { id: 13, label: 'Cancun', tz: 'America/Cancun' },
    { id: 77, label: 'Tijuana', tz: 'America/Tijuana' },
    { id: 123, label: 'Mexico', tz: 'America/Mexico_City' },

    // --- South America ---
    { id: 14, label: 'Lima', tz: 'America/Lima' },
    { id: 124, label: 'Peru', tz: 'America/Lima' },
    { id: 15, label: 'Buenos Aires', tz: 'America/Argentina/Buenos_Aires' },
    { id: 125, label: 'Argentina', tz: 'America/Argentina/Buenos_Aires' },
    { id: 16, label: 'São Paulo', tz: 'America/Sao_Paulo' },
    { id: 17, label: 'Rio de Janeiro', tz: 'America/Sao_Paulo' },
    { id: 78, label: 'Brasília', tz: 'America/Sao_Paulo' },
    { id: 126, label: 'Brazil', tz: 'America/Sao_Paulo' },
    { id: 18, label: 'Santiago', tz: 'America/Santiago' },
    { id: 127, label: 'Chile', tz: 'America/Santiago' },
    { id: 19, label: 'Bogotá', tz: 'America/Bogota' },
    { id: 128, label: 'Colombia', tz: 'America/Bogota' },
    { id: 20, label: 'Caracas', tz: 'America/Caracas' },
    { id: 129, label: 'Venezuela', tz: 'America/Caracas' },
    { id: 21, label: 'La Paz', tz: 'America/La_Paz' },
    { id: 130, label: 'Bolivia', tz: 'America/La_Paz' },
    { id: 79, label: 'Montevideo', tz: 'America/Montevideo' },
    { id: 131, label: 'Uruguay', tz: 'America/Montevideo' },
    { id: 80, label: 'Quito', tz: 'America/Guayaquil' },
    { id: 132, label: 'Ecuador', tz: 'America/Guayaquil' },

    // --- Europe ---
    { id: 22, label: 'London', tz: 'Europe/London' },
    { id: 23, label: 'Dublin', tz: 'Europe/Dublin' },
    { id: 133, label: 'Ireland', tz: 'Europe/Dublin' },
    { id: 81, label: 'Manchester', tz: 'Europe/London' },
    { id: 82, label: 'Edinburgh', tz: 'Europe/London' },
    { id: 117, label: 'England', tz: 'Europe/London' },
    { id: 118, label: 'Scotland', tz: 'Europe/London' },
    { id: 134, label: 'United Kingdom', tz: 'Europe/London' },
    { id: 24, label: 'Paris', tz: 'Europe/Paris' },
    { id: 135, label: 'France', tz: 'Europe/Paris' },
    { id: 25, label: 'Berlin', tz: 'Europe/Berlin' },
    { id: 83, label: 'Munich', tz: 'Europe/Berlin' },
    { id: 84, label: 'Hamburg', tz: 'Europe/Berlin' },
    { id: 136, label: 'Germany', tz: 'Europe/Berlin' },
    { id: 26, label: 'Madrid', tz: 'Europe/Madrid' },
    { id: 85, label: 'Barcelona', tz: 'Europe/Madrid' },
    { id: 137, label: 'Spain', tz: 'Europe/Madrid' },
    { id: 27, label: 'Rome', tz: 'Europe/Rome' },
    { id: 86, label: 'Milan', tz: 'Europe/Rome' },
    { id: 138, label: 'Italy', tz: 'Europe/Rome' },
    { id: 28, label: 'Amsterdam', tz: 'Europe/Amsterdam' },
    { id: 139, label: 'Netherlands', tz: 'Europe/Amsterdam' },
    { id: 29, label: 'Oslo', tz: 'Europe/Oslo' },
    { id: 140, label: 'Norway', tz: 'Europe/Oslo' },
    { id: 30, label: 'Stockholm', tz: 'Europe/Stockholm' },
    { id: 141, label: 'Sweden', tz: 'Europe/Stockholm' },
    { id: 31, label: 'Helsinki', tz: 'Europe/Helsinki' },
    { id: 142, label: 'Finland', tz: 'Europe/Helsinki' },
    { id: 32, label: 'Athens', tz: 'Europe/Athens' },
    { id: 143, label: 'Greece', tz: 'Europe/Athens' },
    { id: 33, label: 'Kyiv', tz: 'Europe/Kyiv' },
    { id: 144, label: 'Ukraine', tz: 'Europe/Kyiv' },
    { id: 34, label: 'Moscow', tz: 'Europe/Moscow' },
    { id: 87, label: 'Saint Petersburg', tz: 'Europe/Moscow' },
    { id: 35, label: 'Istanbul', tz: 'Europe/Istanbul' },
    { id: 145, label: 'Turkey', tz: 'Europe/Istanbul' },
    { id: 88, label: 'Lisbon', tz: 'Europe/Lisbon' },
    { id: 146, label: 'Portugal', tz: 'Europe/Lisbon' },
    { id: 89, label: 'Prague', tz: 'Europe/Prague' },
    { id: 147, label: 'Czech Republic', tz: 'Europe/Prague' },
    { id: 90, label: 'Vienna', tz: 'Europe/Vienna' },
    { id: 148, label: 'Austria', tz: 'Europe/Vienna' },
    { id: 91, label: 'Zurich', tz: 'Europe/Zurich' },
    { id: 149, label: 'Switzerland', tz: 'Europe/Zurich' },
    { id: 92, label: 'Brussels', tz: 'Europe/Brussels' },
    { id: 150, label: 'Belgium', tz: 'Europe/Brussels' },
    { id: 93, label: 'Copenhagen', tz: 'Europe/Copenhagen' },
    { id: 151, label: 'Denmark', tz: 'Europe/Copenhagen' },
    { id: 94, label: 'Warsaw', tz: 'Europe/Warsaw' },
    { id: 152, label: 'Poland', tz: 'Europe/Warsaw' },

    // --- Asia ---
    { id: 36, label: 'Tokyo', tz: 'Asia/Tokyo' },
    { id: 153, label: 'Japan', tz: 'Asia/Tokyo' },
    { id: 37, label: 'Seoul', tz: 'Asia/Seoul' },
    { id: 154, label: 'South Korea', tz: 'Asia/Seoul' },
    { id: 38, label: 'Beijing', tz: 'Asia/Shanghai' },
    { id: 39, label: 'Shanghai', tz: 'Asia/Shanghai' },
    { id: 40, label: 'Hong Kong', tz: 'Asia/Hong_Kong' },
    { id: 41, label: 'Singapore', tz: 'Asia/Singapore' },
    { id: 42, label: 'Bangkok', tz: 'Asia/Bangkok' },
    { id: 155, label: 'Thailand', tz: 'Asia/Bangkok' },
    { id: 43, label: 'Dubai', tz: 'Asia/Dubai' },
    { id: 95, label: 'Abu Dhabi', tz: 'Asia/Dubai' },
    { id: 156, label: 'United Arab Emirates', tz: 'Asia/Dubai' },
    { id: 44, label: 'Mumbai', tz: 'Asia/Kolkata' },
    { id: 45, label: 'New Delhi', tz: 'Asia/Kolkata' },
    { id: 96, label: 'Bangalore', tz: 'Asia/Kolkata' },
    { id: 46, label: 'Jerusalem', tz: 'Asia/Jerusalem' },
    { id: 157, label: 'Israel', tz: 'Asia/Jerusalem' },
    { id: 47, label: 'Jakarta', tz: 'Asia/Jakarta' },
    { id: 48, label: 'Manila', tz: 'Asia/Manila' },
    { id: 158, label: 'Philippines', tz: 'Asia/Manila' },
    { id: 97, label: 'Taipei', tz: 'Asia/Taipei' },
    { id: 159, label: 'Taiwan', tz: 'Asia/Taipei' },
    { id: 98, label: 'Kuala Lumpur', tz: 'Asia/Kuala_Lumpur' },
    { id: 160, label: 'Malaysia', tz: 'Asia/Kuala_Lumpur' },
    { id: 99, label: 'Ho Chi Minh City', tz: 'Asia/Ho_Chi_Minh' },
    { id: 161, label: 'Vietnam', tz: 'Asia/Ho_Chi_Minh' },
    { id: 100, label: 'Riyadh', tz: 'Asia/Riyadh' },
    { id: 162, label: 'Saudi Arabia', tz: 'Asia/Riyadh' },
    { id: 101, label: 'Doha', tz: 'Asia/Qatar' },
    { id: 163, label: 'Qatar', tz: 'Asia/Qatar' },

    // --- Africa ---
    { id: 49, label: 'Cairo', tz: 'Africa/Cairo' },
    { id: 164, label: 'Egypt', tz: 'Africa/Cairo' },
    { id: 50, label: 'Johannesburg', tz: 'Africa/Johannesburg' },
    { id: 102, label: 'Cape Town', tz: 'Africa/Johannesburg' },
    { id: 165, label: 'South Africa', tz: 'Africa/Johannesburg' },
    { id: 51, label: 'Nairobi', tz: 'Africa/Nairobi' },
    { id: 166, label: 'Kenya', tz: 'Africa/Nairobi' },
    { id: 52, label: 'Lagos', tz: 'Africa/Lagos' },
    { id: 167, label: 'Nigeria', tz: 'Africa/Lagos' },
    { id: 53, label: 'Casablanca', tz: 'Africa/Casablanca' },
    { id: 168, label: 'Morocco', tz: 'Africa/Casablanca' },
    { id: 103, label: 'Accra', tz: 'Africa/Accra' },
    { id: 169, label: 'Ghana', tz: 'Africa/Accra' },
    { id: 104, label: 'Algiers', tz: 'Africa/Algiers' },
    { id: 170, label: 'Algeria', tz: 'Africa/Algiers' },

    // --- Oceania ---
    { id: 54, label: 'Sydney', tz: 'Australia/Sydney' },
    { id: 55, label: 'Melbourne', tz: 'Australia/Melbourne' },
    { id: 56, label: 'Brisbane', tz: 'Australia/Brisbane' },
    { id: 57, label: 'Perth', tz: 'Australia/Perth' },
    { id: 58, label: 'Adelaide', tz: 'Australia/Adelaide' },
    { id: 59, label: 'Darwin', tz: 'Australia/Darwin' },
    { id: 105, label: 'Canberra', tz: 'Australia/Sydney' },
    // Australian States
    { id: 119, label: 'New South Wales', tz: 'Australia/Sydney' },
    { id: 120, label: 'Victoria', tz: 'Australia/Melbourne' },
    { id: 121, label: 'Queensland', tz: 'Australia/Brisbane' },
    { id: 122, label: 'Western Australia', tz: 'Australia/Perth' },
    { id: 60, label: 'Auckland', tz: 'Pacific/Auckland' },
    { id: 106, label: 'Wellington', tz: 'Pacific/Auckland' },
    { id: 171, label: 'New Zealand', tz: 'Pacific/Auckland' },
    { id: 61, label: 'Fiji', tz: 'Pacific/Fiji' },
];