export type TimezoneOption = {
    id: number;
    label: string;
    tz: string;
    countryCode: string;
    region?: string;
};

export const timezones: TimezoneOption[] = [
    // --- North America ---
    // United States
    { id: 1, label: 'New York', tz: 'America/New_York', countryCode: 'US', region: 'US-NY' },
    { id: 2, label: 'Chicago', tz: 'America/Chicago', countryCode: 'US', region: 'US-IL' },
    { id: 3, label: 'Denver', tz: 'America/Denver', countryCode: 'US', region: 'US-CO' },
    { id: 4, label: 'Los Angeles', tz: 'America/Los_Angeles', countryCode: 'US', region: 'US-CA' },
    { id: 5, label: 'Anchorage', tz: 'America/Anchorage', countryCode: 'US', region: 'US-AK' },
    { id: 6, label: 'Honolulu', tz: 'Pacific/Honolulu', countryCode: 'US', region: 'US-HI' },
    { id: 7, label: 'Phoenix', tz: 'America/Phoenix', countryCode: 'US', region: 'US-AZ' },
    { id: 62, label: 'Atlanta', tz: 'America/New_York', countryCode: 'US', region: 'US-GA' },
    { id: 63, label: 'Boston', tz: 'America/New_York', countryCode: 'US', region: 'US-MA' },
    { id: 64, label: 'Miami', tz: 'America/New_York', countryCode: 'US', region: 'US-FL' },
    { id: 65, label: 'Washington D.C.', tz: 'America/New_York', countryCode: 'US', region: 'US-DC' },
    { id: 66, label: 'Dallas', tz: 'America/Chicago', countryCode: 'US', region: 'US-TX' },
    { id: 67, label: 'Houston', tz: 'America/Chicago', countryCode: 'US', region: 'US-TX' },
    { id: 68, label: 'New Orleans', tz: 'America/Chicago', countryCode: 'US', region: 'US-LA' },
    { id: 69, label: 'Salt Lake City', tz: 'America/Denver', countryCode: 'US', region: 'US-UT' },
    { id: 70, label: 'San Francisco', tz: 'America/Los_Angeles', countryCode: 'US', region: 'US-CA' },
    { id: 71, label: 'Seattle', tz: 'America/Los_Angeles', countryCode: 'US', region: 'US-WA' },
    { id: 72, label: 'Las Vegas', tz: 'America/Los_Angeles', countryCode: 'US', region: 'US-NV' },
    { id: 172, label: 'Orlando', tz: 'America/New_York', countryCode: 'US', region: 'US-FL' },
    { id: 173, label: 'Grand Canyon', tz: 'America/Phoenix', countryCode: 'US', region: 'US-AZ' },
    { id: 205, label: 'Philadelphia', tz: 'America/New_York', countryCode: 'US', region: 'US-PA' },
    // US States & Regions
    { id: 107, label: 'California', tz: 'America/Los_Angeles', countryCode: 'US', region: 'US-CA' },
    { id: 108, label: 'Texas', tz: 'America/Chicago', countryCode: 'US', region: 'US-TX' },
    { id: 109, label: 'Florida', tz: 'America/New_York', countryCode: 'US', region: 'US-FL' },
    { id: 110, label: 'Arizona', tz: 'America/Phoenix', countryCode: 'US', region: 'US-AZ' },
    { id: 111, label: 'Colorado', tz: 'America/Denver', countryCode: 'US', region: 'US-CO' },
    { id: 112, label: 'Illinois', tz: 'America/Chicago', countryCode: 'US', region: 'US-IL' },

    // Canada
    { id: 8, label: 'Toronto', tz: 'America/Toronto', countryCode: 'CA', region: 'CA-ON' },
    { id: 9, label: 'Vancouver', tz: 'America/Vancouver', countryCode: 'CA', region: 'CA-BC' },
    { id: 10, label: 'Halifax', tz: 'America/Halifax', countryCode: 'CA', region: 'CA-NS' },
    { id: 11, label: 'Winnipeg', tz: 'America/Winnipeg', countryCode: 'CA', region: 'CA-MB' },
    { id: 73, label: 'Montreal', tz: 'America/Toronto', countryCode: 'CA', region: 'CA-QC' },
    { id: 74, label: 'Ottawa', tz: 'America/Toronto', countryCode: 'CA', region: 'CA-ON' },
    { id: 75, label: 'Calgary', tz: 'America/Edmonton', countryCode: 'CA', region: 'CA-AB' },
    { id: 76, label: 'Edmonton', tz: 'America/Edmonton', countryCode: 'CA', region: 'CA-AB' },
    { id: 174, label: 'Banff', tz: 'America/Edmonton', countryCode: 'CA', region: 'CA-AB' },
    // Canadian Provinces
    { id: 113, label: 'Ontario', tz: 'America/Toronto', countryCode: 'CA', region: 'CA-ON' },
    { id: 114, label: 'Quebec', tz: 'America/Toronto', countryCode: 'CA', region: 'CA-QC' },
    { id: 115, label: 'British Columbia', tz: 'America/Vancouver', countryCode: 'CA', region: 'CA-BC' },
    { id: 116, label: 'Alberta', tz: 'America/Edmonton', countryCode: 'CA', region: 'CA-AB' },

    // Mexico
    { id: 12, label: 'Mexico City', tz: 'America/Mexico_City', countryCode: 'MX' },
    { id: 13, label: 'Cancun', tz: 'America/Cancun', countryCode: 'MX' },
    { id: 77, label: 'Tijuana', tz: 'America/Tijuana', countryCode: 'MX' },
    { id: 175, label: 'Guadalajara', tz: 'America/Mexico_City', countryCode: 'MX' },
    { id: 123, label: 'Mexico', tz: 'America/Mexico_City', countryCode: 'MX' },

    // --- South America ---
    { id: 14, label: 'Lima', tz: 'America/Lima', countryCode: 'PE' },
    { id: 176, label: 'Cusco', tz: 'America/Lima', countryCode: 'PE' },
    { id: 124, label: 'Peru', tz: 'America/Lima', countryCode: 'PE' },
    { id: 15, label: 'Buenos Aires', tz: 'America/Argentina/Buenos_Aires', countryCode: 'AR' },
    { id: 177, label: 'Ushuaia', tz: 'America/Argentina/Buenos_Aires', countryCode: 'AR' },
    { id: 125, label: 'Argentina', tz: 'America/Argentina/Buenos_Aires', countryCode: 'AR' },
    { id: 16, label: 'São Paulo', tz: 'America/Sao_Paulo', countryCode: 'BR' },
    { id: 17, label: 'Rio de Janeiro', tz: 'America/Sao_Paulo', countryCode: 'BR' },
    { id: 178, label: 'Salvador', tz: 'America/Sao_Paulo', countryCode: 'BR' },
    { id: 78, label: 'Brasília', tz: 'America/Sao_Paulo', countryCode: 'BR' },
    { id: 126, label: 'Brazil', tz: 'America/Sao_Paulo', countryCode: 'BR' },
    { id: 18, label: 'Santiago', tz: 'America/Santiago', countryCode: 'CL' },
    { id: 179, label: 'Valparaíso', tz: 'America/Santiago', countryCode: 'CL' },
    { id: 127, label: 'Chile', tz: 'America/Santiago', countryCode: 'CL' },
    { id: 19, label: 'Bogotá', tz: 'America/Bogota', countryCode: 'CO' },
    { id: 180, label: 'Cartagena', tz: 'America/Bogota', countryCode: 'CO' },
    { id: 207, label: 'Medellín', tz: 'America/Bogota', countryCode: 'CO' },
    { id: 128, label: 'Colombia', tz: 'America/Bogota', countryCode: 'CO' },
    { id: 20, label: 'Caracas', tz: 'America/Caracas', countryCode: 'VE' },
    { id: 129, label: 'Venezuela', tz: 'America/Caracas', countryCode: 'VE' },
    { id: 21, label: 'La Paz', tz: 'America/La_Paz', countryCode: 'BO' },
    { id: 130, label: 'Bolivia', tz: 'America/La_Paz', countryCode: 'BO' },
    { id: 79, label: 'Montevideo', tz: 'America/Montevideo', countryCode: 'UY' },
    { id: 131, label: 'Uruguay', tz: 'America/Montevideo', countryCode: 'UY' },
    { id: 80, label: 'Quito', tz: 'America/Guayaquil', countryCode: 'EC' },
    { id: 132, label: 'Ecuador', tz: 'America/Guayaquil', countryCode: 'EC' },

    // --- Europe ---
    { id: 22, label: 'London', tz: 'Europe/London', countryCode: 'GB', region: 'GB-ENG' },
    { id: 23, label: 'Dublin', tz: 'Europe/Dublin', countryCode: 'IE' },
    { id: 133, label: 'Ireland', tz: 'Europe/Dublin', countryCode: 'IE' },
    { id: 81, label: 'Manchester', tz: 'Europe/London', countryCode: 'GB', region: 'GB-ENG' },
    { id: 82, label: 'Edinburgh', tz: 'Europe/London', countryCode: 'GB', region: 'GB-SCT' },
    { id: 181, label: 'Stonehenge', tz: 'Europe/London', countryCode: 'GB', region: 'GB-ENG' },
    { id: 117, label: 'England', tz: 'Europe/London', countryCode: 'GB', region: 'GB-ENG' },
    { id: 118, label: 'Scotland', tz: 'Europe/London', countryCode: 'GB', region: 'GB-SCT' },
    { id: 134, label: 'United Kingdom', tz: 'Europe/London', countryCode: 'GB' },
    { id: 24, label: 'Paris', tz: 'Europe/Paris', countryCode: 'FR' },
    { id: 182, label: 'Nice', tz: 'Europe/Paris', countryCode: 'FR' },
    { id: 135, label: 'France', tz: 'Europe/Paris', countryCode: 'FR' },
    { id: 25, label: 'Berlin', tz: 'Europe/Berlin', countryCode: 'DE', region: 'DE-BE' },
    { id: 83, label: 'Munich', tz: 'Europe/Berlin', countryCode: 'DE', region: 'DE-BY' },
    { id: 84, label: 'Hamburg', tz: 'Europe/Berlin', countryCode: 'DE', region: 'DE-HH' },
    { id: 183, label: 'Neuschwanstein Castle', tz: 'Europe/Berlin', countryCode: 'DE', region: 'DE-BY' },
    { id: 206, label: 'Frankfurt', tz: 'Europe/Berlin', countryCode: 'DE', region: 'DE-HE' },
    { id: 136, label: 'Germany', tz: 'Europe/Berlin', countryCode: 'DE' },
    { id: 26, label: 'Madrid', tz: 'Europe/Madrid', countryCode: 'ES' },
    { id: 85, label: 'Barcelona', tz: 'Europe/Madrid', countryCode: 'ES' },
    { id: 184, label: 'Seville', tz: 'Europe/Madrid', countryCode: 'ES' },
    { id: 209, label: 'Tenerife (Canary Islands)', tz: 'Atlantic/Canary', countryCode: 'ES' },
    { id: 137, label: 'Spain', tz: 'Europe/Madrid', countryCode: 'ES' },
    { id: 27, label: 'Rome', tz: 'Europe/Rome', countryCode: 'IT' },
    { id: 86, label: 'Milan', tz: 'Europe/Rome', countryCode: 'IT' },
    { id: 185, label: 'Venice', tz: 'Europe/Rome', countryCode: 'IT' },
    { id: 186, label: 'Florence', tz: 'Europe/Rome', countryCode: 'IT' },
    { id: 138, label: 'Italy', tz: 'Europe/Rome', countryCode: 'IT' },
    { id: 28, label: 'Amsterdam', tz: 'Europe/Amsterdam', countryCode: 'NL' },
    { id: 139, label: 'Netherlands', tz: 'Europe/Amsterdam', countryCode: 'NL' },
    { id: 29, label: 'Oslo', tz: 'Europe/Oslo', countryCode: 'NO' },
    { id: 140, label: 'Norway', tz: 'Europe/Oslo', countryCode: 'NO' },
    { id: 30, label: 'Stockholm', tz: 'Europe/Stockholm', countryCode: 'SE' },
    { id: 141, label: 'Sweden', tz: 'Europe/Stockholm', countryCode: 'SE' },
    { id: 31, label: 'Helsinki', tz: 'Europe/Helsinki', countryCode: 'FI' },
    { id: 142, label: 'Finland', tz: 'Europe/Helsinki', countryCode: 'FI' },
    { id: 32, label: 'Athens', tz: 'Europe/Athens', countryCode: 'GR' },
    { id: 187, label: 'Santorini', tz: 'Europe/Athens', countryCode: 'GR' },
    { id: 143, label: 'Greece', tz: 'Europe/Athens', countryCode: 'GR' },
    { id: 33, label: 'Kyiv', tz: 'Europe/Kyiv', countryCode: 'UA' },
    { id: 144, label: 'Ukraine', tz: 'Europe/Kyiv', countryCode: 'UA' },
    { id: 34, label: 'Moscow', tz: 'Europe/Moscow', countryCode: 'RU' },
    { id: 87, label: 'Saint Petersburg', tz: 'Europe/Moscow', countryCode: 'RU' },
    { id: 35, label: 'Istanbul', tz: 'Europe/Istanbul', countryCode: 'TR' },
    { id: 188, label: 'Cappadocia', tz: 'Europe/Istanbul', countryCode: 'TR' },
    { id: 145, label: 'Turkey', tz: 'Europe/Istanbul', countryCode: 'TR' },
    { id: 88, label: 'Lisbon', tz: 'Europe/Lisbon', countryCode: 'PT' },
    { id: 189, label: 'Porto', tz: 'Europe/Lisbon', countryCode: 'PT' },
    { id: 146, label: 'Portugal', tz: 'Europe/Lisbon', countryCode: 'PT' },
    { id: 89, label: 'Prague', tz: 'Europe/Prague', countryCode: 'CZ' },
    { id: 147, label: 'Czech Republic', tz: 'Europe/Prague', countryCode: 'CZ' },
    { id: 90, label: 'Vienna', tz: 'Europe/Vienna', countryCode: 'AT' },
    { id: 148, label: 'Austria', tz: 'Europe/Vienna', countryCode: 'AT' },
    { id: 91, label: 'Zurich', tz: 'Europe/Zurich', countryCode: 'CH' },
    { id: 190, label: 'Geneva', tz: 'Europe/Zurich', countryCode: 'CH' },
    { id: 149, label: 'Switzerland', tz: 'Europe/Zurich', countryCode: 'CH' },
    { id: 92, label: 'Brussels', tz: 'Europe/Brussels', countryCode: 'BE' },
    { id: 150, label: 'Belgium', tz: 'Europe/Brussels', countryCode: 'BE' },
    { id: 93, label: 'Copenhagen', tz: 'Europe/Copenhagen', countryCode: 'DK' },
    { id: 151, label: 'Denmark', tz: 'Europe/Copenhagen', countryCode: 'DK' },
    { id: 94, label: 'Warsaw', tz: 'Europe/Warsaw', countryCode: 'PL' },
    { id: 210, label: 'Krakow', tz: 'Europe/Warsaw', countryCode: 'PL' },
    { id: 152, label: 'Poland', tz: 'Europe/Warsaw', countryCode: 'PL' },
    { id: 208, label: 'Budapest', tz: 'Europe/Budapest', countryCode: 'HU' },
    { id: 213, label: 'Reykjavik', tz: 'Atlantic/Reykjavik', countryCode: 'IS' },
    { id: 214, label: 'Dubrovnik', tz: 'Europe/Zagreb', countryCode: 'HR' },

    // --- Additions for Europe ---
    { id: 220, label: 'Hungary', tz: 'Europe/Budapest', countryCode: 'HU' },
    { id: 221, label: 'Iceland', tz: 'Atlantic/Reykjavik', countryCode: 'IS' },
    { id: 222, label: 'Croatia', tz: 'Europe/Zagreb', countryCode: 'HR' },

    // --- Asia ---
    { id: 36, label: 'Tokyo', tz: 'Asia/Tokyo', countryCode: 'JP' },
    { id: 191, label: 'Kyoto', tz: 'Asia/Tokyo', countryCode: 'JP' },
    { id: 192, label: 'Mount Fuji', tz: 'Asia/Tokyo', countryCode: 'JP' },
    { id: 153, label: 'Japan', tz: 'Asia/Tokyo', countryCode: 'JP' },
    { id: 37, label: 'Seoul', tz: 'Asia/Seoul', countryCode: 'KR' },
    { id: 154, label: 'South Korea', tz: 'Asia/Seoul', countryCode: 'KR' },
    { id: 38, label: 'Beijing', tz: 'Asia/Shanghai', countryCode: 'CN' },
    { id: 39, label: 'Shanghai', tz: 'Asia/Shanghai', countryCode: 'CN' },
    { id: 193, label: 'Great Wall of China', tz: 'Asia/Shanghai', countryCode: 'CN' },
    { id: 40, label: 'Hong Kong', tz: 'Asia/Hong_Kong', countryCode: 'HK' },
    { id: 41, label: 'Singapore', tz: 'Asia/Singapore', countryCode: 'SG' },
    { id: 42, label: 'Bangkok', tz: 'Asia/Bangkok', countryCode: 'TH' },
    { id: 194, label: 'Phuket', tz: 'Asia/Bangkok', countryCode: 'TH' },
    { id: 211, label: 'Chiang Mai', tz: 'Asia/Bangkok', countryCode: 'TH' },
    { id: 155, label: 'Thailand', tz: 'Asia/Bangkok', countryCode: 'TH' },
    { id: 43, label: 'Dubai', tz: 'Asia/Dubai', countryCode: 'AE' },
    { id: 95, label: 'Abu Dhabi', tz: 'Asia/Dubai', countryCode: 'AE' },
    { id: 156, label: 'United Arab Emirates', tz: 'Asia/Dubai', countryCode: 'AE' },
    { id: 44, label: 'Mumbai', tz: 'Asia/Kolkata', countryCode: 'IN' },
    { id: 45, label: 'New Delhi', tz: 'Asia/Kolkata', countryCode: 'IN' },
    { id: 96, label: 'Bangalore', tz: 'Asia/Kolkata', countryCode: 'IN' },
    { id: 195, label: 'Agra', tz: 'Asia/Kolkata', countryCode: 'IN' },
    { id: 46, label: 'Jerusalem', tz: 'Asia/Jerusalem', countryCode: 'IL' },
    { id: 157, label: 'Israel', tz: 'Asia/Jerusalem', countryCode: 'IL' },
    { id: 47, label: 'Jakarta', tz: 'Asia/Jakarta', countryCode: 'ID' },
    { id: 196, label: 'Bali', tz: 'Asia/Makassar', countryCode: 'ID' },
    { id: 48, label: 'Manila', tz: 'Asia/Manila', countryCode: 'PH' },
    { id: 158, label: 'Philippines', tz: 'Asia/Manila', countryCode: 'PH' },
    { id: 97, label: 'Taipei', tz: 'Asia/Taipei', countryCode: 'TW' },
    { id: 159, label: 'Taiwan', tz: 'Asia/Taipei', countryCode: 'TW' },
    { id: 98, label: 'Kuala Lumpur', tz: 'Asia/Kuala_Lumpur', countryCode: 'MY' },
    { id: 160, label: 'Malaysia', tz: 'Asia/Kuala_Lumpur', countryCode: 'MY' },
    { id: 99, label: 'Ho Chi Minh City', tz: 'Asia/Ho_Chi_Minh', countryCode: 'VN' },
    { id: 197, label: 'Ha Long Bay', tz: 'Asia/Ho_Chi_Minh', countryCode: 'VN' },
    { id: 212, label: 'Da Nang', tz: 'Asia/Ho_Chi_Minh', countryCode: 'VN' },
    { id: 161, label: 'Vietnam', tz: 'Asia/Ho_Chi_Minh', countryCode: 'VN' },
    { id: 100, label: 'Riyadh', tz: 'Asia/Riyadh', countryCode: 'SA' },
    { id: 162, label: 'Saudi Arabia', tz: 'Asia/Riyadh', countryCode: 'SA' },
    { id: 101, label: 'Doha', tz: 'Asia/Qatar', countryCode: 'QA' },
    { id: 163, label: 'Qatar', tz: 'Asia/Qatar', countryCode: 'QA' },
    { id: 215, label: 'Siem Reap', tz: 'Asia/Phnom_Penh', countryCode: 'KH' },
    { id: 216, label: 'Kathmandu', tz: 'Asia/Kathmandu', countryCode: 'NP' },
    { id: 217, label: 'Petra', tz: 'Asia/Amman', countryCode: 'JO' },

    // --- Africa ---
    { id: 49, label: 'Cairo', tz: 'Africa/Cairo', countryCode: 'EG' },
    { id: 198, label: 'Giza', tz: 'Africa/Cairo', countryCode: 'EG' },
    { id: 199, label: 'Luxor', tz: 'Africa/Cairo', countryCode: 'EG' },
    { id: 164, label: 'Egypt', tz: 'Africa/Cairo', countryCode: 'EG' },
    { id: 50, label: 'Johannesburg', tz: 'Africa/Johannesburg', countryCode: 'ZA' },
    { id: 102, label: 'Cape Town', tz: 'Africa/Johannesburg', countryCode: 'ZA' },
    { id: 200, label: 'Kruger National Park', tz: 'Africa/Johannesburg', countryCode: 'ZA' },
    { id: 165, label: 'South Africa', tz: 'Africa/Johannesburg', countryCode: 'ZA' },
    { id: 51, label: 'Nairobi', tz: 'Africa/Nairobi', countryCode: 'KE' },
    { id: 166, label: 'Kenya', tz: 'Africa/Nairobi', countryCode: 'KE' },
    { id: 52, label: 'Lagos', tz: 'Africa/Lagos', countryCode: 'NG' },
    { id: 167, label: 'Nigeria', tz: 'Africa/Lagos', countryCode: 'NG' },
    { id: 53, label: 'Casablanca', tz: 'Africa/Casablanca', countryCode: 'MA' },
    { id: 201, label: 'Marrakech', tz: 'Africa/Casablanca', countryCode: 'MA' },
    { id: 168, label: 'Morocco', tz: 'Africa/Casablanca', countryCode: 'MA' },
    { id: 103, label: 'Accra', tz: 'Africa/Accra', countryCode: 'GH' },
    { id: 169, label: 'Ghana', tz: 'Africa/Accra', countryCode: 'GH' },
    { id: 104, label: 'Algiers', tz: 'Africa/Algiers', countryCode: 'DZ' },
    { id: 170, label: 'Algeria', tz: 'Africa/Algiers', countryCode: 'DZ' },
    { id: 218, label: 'Zanzibar', tz: 'Africa/Dar_es_Salaam', countryCode: 'TZ' },
    { id: 219, label: 'Victoria Falls', tz: 'Africa/Lusaka', countryCode: 'ZM' }, // Could also be ZW (Zimbabwe)

    // --- Additions for Africa ---
    { id: 223, label: 'Tanzania', tz: 'Africa/Dar_es_Salaam', countryCode: 'TZ' },
    { id: 224, label: 'Zimbabwe', tz: 'Africa/Harare', countryCode: 'ZW' },

    // --- Oceania ---
    { id: 54, label: 'Sydney', tz: 'Australia/Sydney', countryCode: 'AU', region: 'AU-NSW' },
    { id: 55, label: 'Melbourne', tz: 'Australia/Melbourne', countryCode: 'AU', region: 'AU-VIC' },
    { id: 56, label: 'Brisbane', tz: 'Australia/Brisbane', countryCode: 'AU', region: 'AU-QLD' },
    { id: 57, label: 'Perth', tz: 'Australia/Perth', countryCode: 'AU', region: 'AU-WA' },
    { id: 58, label: 'Adelaide', tz: 'Australia/Adelaide', countryCode: 'AU', region: 'AU-SA' },
    { id: 59, label: 'Darwin', tz: 'Australia/Darwin', countryCode: 'AU', region: 'AU-NT' },
    { id: 105, label: 'Canberra', tz: 'Australia/Sydney', countryCode: 'AU', region: 'AU-ACT' },
    { id: 202, label: 'Uluru', tz: 'Australia/Darwin', countryCode: 'AU', region: 'AU-NT' },
    { id: 203, label: 'Great Barrier Reef', tz: 'Australia/Brisbane', countryCode: 'AU', region: 'AU-QLD' },
    // Australian States
    { id: 119, label: 'New South Wales', tz: 'Australia/Sydney', countryCode: 'AU', region: 'AU-NSW' },
    { id: 120, label: 'Victoria', tz: 'Australia/Melbourne', countryCode: 'AU', region: 'AU-VIC' },
    { id: 121, label: 'Queensland', tz: 'Australia/Brisbane', countryCode: 'AU', region: 'AU-QLD' },
    { id: 122, label: 'Western Australia', tz: 'Australia/Perth', countryCode: 'AU', region: 'AU-WA' },
    { id: 60, label: 'Auckland', tz: 'Pacific/Auckland', countryCode: 'NZ' },
    { id: 106, label: 'Wellington', tz: 'Pacific/Auckland', countryCode: 'NZ' },
    { id: 204, label: 'Queenstown', tz: 'Pacific/Auckland', countryCode: 'NZ' },
    { id: 171, label: 'New Zealand', tz: 'Pacific/Auckland', countryCode: 'NZ' },
    { id: 61, label: 'Fiji', tz: 'Pacific/Fiji', countryCode: 'FJ' },
];